
[functions.sepay-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/sepay-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/sepay-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/sepay-webhook/*.html" ]

[functions.webhook-payment]
enabled = true
verify_jwt = false
entrypoint = "./functions/webhook-payment/index.ts"

[functions.process-payment]
enabled = true
verify_jwt = true
entrypoint = "./functions/process-payment/index.ts"

[functions.run-utility-billing]
enabled = true
verify_jwt = false
entrypoint = "./functions/run-utility-billing/index.ts"

[functions.create-contract]
enabled = true
verify_jwt = true
entrypoint = "./functions/create-contract/index.ts"

[functions.create-user]
enabled = true
verify_jwt = true
entrypoint = "./functions/create-user/index.ts"

[functions.create-utility-invoice]
enabled = true
verify_jwt = false
entrypoint = "./functions/create-utility-invoice/index.ts"

[db.seed]
enabled = true
sql_paths = ["./seed.sql", "./seeds/domain_demo_seed.sql"]
