begin;

do $$
begin
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'smartstay'
      and t.typname = 'payment_status'
  ) then
    create type smartstay.payment_status as enum (
      'cho_xu_ly',
      'da_gui',
      'dang_xu_ly',
      'thanh_cong',
      'that_bai',
      'da_huy',
      'bi_tu_choi',
      'da_hoan_tien'
    );
  end if;
end
$$;

comment on type smartstay.payment_status is
'Trang thai xu ly thanh toan.
cho_xu_ly = Cho xu ly (vua tao, chua lam gi)
da_gui = Da gui yeu cau (tenant da submit, cho admin hoac gateway)
dang_xu_ly = Dang xu ly (gateway dang xu ly)
thanh_cong = Thanh toan thanh cong
that_bai = Thanh toan that bai
da_huy = Da huy (tenant huy truoc khi xu ly)
bi_tu_choi = Bi tu choi (admin reject)
da_hoan_tien = Da hoan tien';

do $$
begin
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'smartstay'
      and t.typname = 'payment_attempt_method'
  ) then
    create type smartstay.payment_attempt_method as enum (
      'momo_online',
      'tien_mat',
      'chuyen_khoan'
    );
  end if;
end
$$;

comment on type smartstay.payment_attempt_method is
'Phuong thuc payment attempt.
momo_online = Thanh toan MoMo online qua gateway
tien_mat = Thu tien mat, admin/thu ngan duyet tay
chuyen_khoan = Tenant chuyen khoan va upload bien lai, admin duyet tay';

create table if not exists smartstay.payment_attempts (
  id bigint generated by default as identity primary key,
  uuid uuid not null default gen_random_uuid(),
  invoice_id integer not null references smartstay.invoices(id) on delete restrict,
  initiated_by uuid null references smartstay.profiles(id),
  method smartstay.payment_attempt_method not null,
  amount numeric not null check (amount > 0),
  status smartstay.payment_status not null default 'cho_xu_ly',
  idempotency_key text null,
  receipt_url text null,
  reference_number varchar null,
  bank_name varchar null,
  gateway_order_id text null,
  gateway_request_id text null,
  gateway_transaction_id text null,
  gateway_payload jsonb not null default '{}'::jsonb,
  notes text null,
  rejection_reason text null,
  payment_id bigint null references smartstay.payments(id),
  approved_at timestamptz null,
  approved_by uuid null references smartstay.profiles(id),
  rejected_at timestamptz null,
  rejected_by uuid null references smartstay.profiles(id),
  cancelled_at timestamptz null,
  cancelled_by uuid null references smartstay.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint payment_attempts_uuid_key unique (uuid)
);

comment on table smartstay.payment_attempts is 'Bang luu yeu cau thanh toan tu tenant hoac gateway. Khong phai so cai thu tien da xac nhan.';
comment on column smartstay.payment_attempts.status is 'Trang thai xu ly cua yeu cau thanh toan.';
comment on column smartstay.payment_attempts.idempotency_key is 'Khoa chong xu ly lap cho IPN va retry request.';
comment on column smartstay.payment_attempts.gateway_payload is 'Payload gateway gan nhat lien quan den yeu cau thanh toan.';

create index if not exists payment_attempts_invoice_id_idx
  on smartstay.payment_attempts (invoice_id, created_at desc);

create index if not exists payment_attempts_status_idx
  on smartstay.payment_attempts (status, created_at desc);

create unique index if not exists payment_attempts_idempotency_key_uidx
  on smartstay.payment_attempts (idempotency_key)
  where idempotency_key is not null;

create unique index if not exists payment_attempts_gateway_order_id_uidx
  on smartstay.payment_attempts (gateway_order_id)
  where gateway_order_id is not null;

create unique index if not exists payment_attempts_payment_id_uidx
  on smartstay.payment_attempts (payment_id)
  where payment_id is not null;

alter table smartstay.payments
  add column if not exists status smartstay.payment_status,
  add column if not exists confirmation_source text,
  add column if not exists applied_at timestamptz,
  add column if not exists applied_by uuid references smartstay.profiles(id),
  add column if not exists payment_attempt_id bigint references smartstay.payment_attempts(id);

comment on column smartstay.payments.status is 'Trang thai dong tien da ghi nhan. Tuong thich nguoc voi du lieu cu.';
comment on column smartstay.payments.confirmation_source is 'Nguon xac nhan thanh toan: momo_ipn, admin_thu_cong, tien_mat, doi_soat_ngan_hang.';
comment on column smartstay.payments.applied_at is 'Thoi diem dong tien da duoc cong vao invoice va balance. Dung de chong double-apply.';
comment on column smartstay.payments.payment_attempt_id is 'Lien ket nguoc ve payment_attempt da sinh ra payment confirmed nay.';

create unique index if not exists payments_payment_attempt_id_uidx
  on smartstay.payments (payment_attempt_id)
  where payment_attempt_id is not null;

create index if not exists payments_status_idx
  on smartstay.payments (status, confirmed_at desc);

create index if not exists payments_invoice_applied_idx
  on smartstay.payments (invoice_id, applied_at);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'payments_confirmation_source_check'
      and conrelid = 'smartstay.payments'::regclass
  ) then
    alter table smartstay.payments
      add constraint payments_confirmation_source_check
      check (
        confirmation_source is null
        or confirmation_source in ('momo_ipn', 'admin_thu_cong', 'tien_mat', 'doi_soat_ngan_hang')
      );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'payments_status_confirmed_check'
      and conrelid = 'smartstay.payments'::regclass
  ) then
    alter table smartstay.payments
      add constraint payments_status_confirmed_check
      check (
        status <> 'thanh_cong'
        or confirmed_at is not null
      );
  end if;
end
$$;

create or replace function smartstay.touch_payment_attempt_updated_at()
returns trigger
language plpgsql
set search_path = smartstay, public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_touch_payment_attempt_updated_at on smartstay.payment_attempts;
create trigger trg_touch_payment_attempt_updated_at
before update on smartstay.payment_attempts
for each row
execute function smartstay.touch_payment_attempt_updated_at();

create or replace function smartstay.map_payment_attempt_method(p_method text)
returns smartstay.payment_attempt_method
language plpgsql
immutable
set search_path = smartstay, public
as $$
begin
  case lower(coalesce(trim(p_method), ''))
    when 'momo', 'momo_online' then
      return 'momo_online'::smartstay.payment_attempt_method;
    when 'cash', 'tien_mat' then
      return 'tien_mat'::smartstay.payment_attempt_method;
    when 'bank_transfer', 'chuyen_khoan' then
      return 'chuyen_khoan'::smartstay.payment_attempt_method;
    else
      raise exception 'Unsupported payment method: %', p_method;
  end case;
end;
$$;

create or replace function smartstay.map_legacy_payment_method(
  p_method smartstay.payment_attempt_method
)
returns smartstay.payment_method
language plpgsql
immutable
set search_path = smartstay, public
as $$
begin
  case p_method
    when 'momo_online' then
      return 'momo'::smartstay.payment_method;
    when 'tien_mat' then
      return 'cash'::smartstay.payment_method;
    when 'chuyen_khoan' then
      return 'bank_transfer'::smartstay.payment_method;
    else
      raise exception 'Unsupported mapped method: %', p_method;
  end case;
end;
$$;

create or replace function smartstay.ensure_tenant_balance_record(p_tenant_id bigint)
returns integer
language plpgsql
security definer
set search_path = smartstay, public
as $$
declare
  v_balance_id integer;
begin
  insert into smartstay.tenant_balances (tenant_id, balance, last_updated)
  values (p_tenant_id, 0, now())
  on conflict (tenant_id) do update
    set last_updated = smartstay.tenant_balances.last_updated
  returning id into v_balance_id;

  return v_balance_id;
end;
$$;

create or replace function smartstay.ensure_contract_tenant_balance()
returns trigger
language plpgsql
security definer
set search_path = smartstay, public
as $$
begin
  perform smartstay.ensure_tenant_balance_record(new.tenant_id);
  return new;
end;
$$;

drop trigger if exists trg_contract_tenants_ensure_balance on smartstay.contract_tenants;
create trigger trg_contract_tenants_ensure_balance
after insert on smartstay.contract_tenants
for each row
execute function smartstay.ensure_contract_tenant_balance();

create or replace function smartstay.apply_confirmed_payment(
  p_payment_id bigint,
  p_confirmation_source text,
  p_confirmed_by uuid default null,
  p_fail_if_applied boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path = smartstay, public
as $$
declare
  v_payment record;
  v_invoice record;
  v_primary_tenant_id bigint;
  v_balance_id integer;
  v_balance_before numeric;
  v_balance_after numeric;
  v_new_paid numeric;
  v_new_due numeric;
  v_new_status smartstay.invoice_status;
begin
  select
    p.id,
    p.invoice_id,
    p.amount,
    p.notes,
    p.payment_date,
    p.confirmed_at,
    p.confirmed_by,
    p.applied_at,
    p.status
  into v_payment
  from smartstay.payments p
  where p.id = p_payment_id
  for update;

  if not found then
    raise exception 'Payment not found: %', p_payment_id;
  end if;

  if v_payment.applied_at is not null then
    if p_fail_if_applied then
      raise exception 'Payment % has already been applied to the invoice', p_payment_id;
    end if;

    select
      i.id,
      i.amount_paid,
      i.balance_due,
      i.status
    into v_invoice
    from smartstay.invoices i
    where i.id = v_payment.invoice_id;

    return jsonb_build_object(
      'paymentId', v_payment.id,
      'invoiceId', v_payment.invoice_id,
      'invoiceStatus', v_invoice.status,
      'amountPaid', v_invoice.amount_paid,
      'balanceDue', v_invoice.balance_due
    );
  end if;

  select
    i.id,
    i.contract_id,
    i.invoice_code,
    i.total_amount,
    i.amount_paid,
    i.balance_due,
    i.status
  into v_invoice
  from smartstay.invoices i
  where i.id = v_payment.invoice_id
  for update;

  if not found then
    raise exception 'Invoice not found for payment %', p_payment_id;
  end if;

  v_new_paid := coalesce(v_invoice.amount_paid, 0) + v_payment.amount;
  if v_new_paid > coalesce(v_invoice.total_amount, 0) then
    raise exception 'Payment % would overpay invoice %', p_payment_id, v_invoice.id;
  end if;

  v_new_due := greatest(0, coalesce(v_invoice.total_amount, 0) - v_new_paid);
  v_new_status := case
    when v_new_due = 0 then 'paid'::smartstay.invoice_status
    when v_new_paid > 0 then 'partially_paid'::smartstay.invoice_status
    when v_invoice.status = 'draft' then 'draft'::smartstay.invoice_status
    when v_invoice.status = 'overdue' then 'overdue'::smartstay.invoice_status
    else 'pending_payment'::smartstay.invoice_status
  end;

  update smartstay.payments
  set
    status = 'thanh_cong'::smartstay.payment_status,
    confirmation_source = p_confirmation_source,
    confirmed_at = coalesce(confirmed_at, now()),
    confirmed_by = coalesce(confirmed_by, p_confirmed_by),
    applied_at = now(),
    applied_by = coalesce(applied_by, p_confirmed_by)
  where id = p_payment_id;

  update smartstay.invoices
  set
    amount_paid = v_new_paid,
    status = v_new_status,
    paid_date = case when v_new_due = 0 then coalesce(v_payment.confirmed_at, now()) else null end,
    updated_at = now()
  where id = v_invoice.id;

  select ct.tenant_id
  into v_primary_tenant_id
  from smartstay.contract_tenants ct
  where ct.contract_id = v_invoice.contract_id
  order by ct.is_primary desc, ct.id asc
  limit 1;

  if v_primary_tenant_id is not null then
    v_balance_id := smartstay.ensure_tenant_balance_record(v_primary_tenant_id);

    select balance
    into v_balance_before
    from smartstay.tenant_balances
    where id = v_balance_id
    for update;

    v_balance_after := coalesce(v_balance_before, 0) - v_payment.amount;

    update smartstay.tenant_balances
    set
      balance = v_balance_after,
      last_updated = now()
    where id = v_balance_id;

    insert into smartstay.balance_history (
      tenant_id,
      balance_id,
      transaction_type,
      amount,
      invoice_id,
      payment_id,
      balance_before,
      balance_after,
      notes,
      created_by
    )
    values (
      v_primary_tenant_id,
      v_balance_id,
      'deduction'::smartstay.balance_transaction_type,
      -v_payment.amount,
      v_invoice.id,
      v_payment.id,
      coalesce(v_balance_before, 0),
      v_balance_after,
      format('Ghi nhan thanh toan cho invoice %s', v_invoice.invoice_code),
      p_confirmed_by
    );
  end if;

  return jsonb_build_object(
    'paymentId', v_payment.id,
    'invoiceId', v_invoice.id,
    'invoiceStatus', v_new_status,
    'amountPaid', v_new_paid,
    'balanceDue', v_new_due
  );
end;
$$;

create or replace function smartstay.process_payment(
  p_invoice_id bigint,
  p_amount numeric,
  p_method text,
  p_payment_date timestamp with time zone,
  p_notes text default null,
  p_receipt_url text default null,
  p_reference text default null,
  p_bank_name text default null,
  p_confirmed_by uuid default null,
  p_auto_confirm boolean default true,
  p_idempotency_key text default null,
  p_attempt_status smartstay.payment_status default null
)
returns jsonb
language plpgsql
security definer
set search_path = smartstay, public
as $$
declare
  v_invoice record;
  v_attempt record;
  v_attempt_id bigint;
  v_attempt_method smartstay.payment_attempt_method;
  v_attempt_status smartstay.payment_status;
  v_payment_id bigint;
  v_payment_code text;
  v_result jsonb;
begin
  -- 1) Chot invoice va validate so tien truoc khi tao request.
  select
    i.id,
    i.total_amount,
    i.amount_paid,
    i.balance_due,
    i.status
  into v_invoice
  from smartstay.invoices i
  where i.id = p_invoice_id
  for update;

  if not found then
    raise exception 'Invoice not found: %', p_invoice_id;
  end if;

  if v_invoice.status = 'cancelled' then
    raise exception 'Cancelled invoices cannot receive payments';
  end if;

  if p_amount is null or p_amount <= 0 then
    raise exception 'Payment amount must be greater than 0';
  end if;

  if p_amount > greatest(0, coalesce(v_invoice.balance_due, coalesce(v_invoice.total_amount, 0) - coalesce(v_invoice.amount_paid, 0))) then
    raise exception 'Payment amount exceeds the remaining balance';
  end if;

  v_attempt_method := smartstay.map_payment_attempt_method(p_method);
  v_attempt_status := coalesce(
    p_attempt_status,
    case
      when p_auto_confirm then 'dang_xu_ly'::smartstay.payment_status
      else 'cho_xu_ly'::smartstay.payment_status
    end
  );

  -- 2) Neu co idempotency key thi tra ve ban ghi cu, khong insert lai.
  if p_idempotency_key is not null then
    select
      pa.id,
      pa.status,
      pa.payment_id
    into v_attempt
    from smartstay.payment_attempts pa
    where pa.idempotency_key = p_idempotency_key
    for update;

    if found then
      if v_attempt.payment_id is not null then
        select p.payment_code
        into v_payment_code
        from smartstay.payments p
        where p.id = v_attempt.payment_id;
      end if;

      return jsonb_build_object(
        'attemptId', v_attempt.id,
        'paymentId', v_attempt.payment_id,
        'paymentCode', v_payment_code,
        'attemptStatus', v_attempt.status,
        'invoiceId', p_invoice_id,
        'invoiceStatus', v_invoice.status,
        'amountPaid', v_invoice.amount_paid,
        'balanceDue', coalesce(v_invoice.balance_due, greatest(0, coalesce(v_invoice.total_amount, 0) - coalesce(v_invoice.amount_paid, 0)))
      );
    end if;
  end if;

  -- 3) Tao payment attempt. Day la lop request, chua phai payment confirmed.
  insert into smartstay.payment_attempts (
    invoice_id,
    initiated_by,
    method,
    amount,
    status,
    idempotency_key,
    receipt_url,
    reference_number,
    bank_name,
    gateway_order_id,
    notes
  )
  values (
    p_invoice_id,
    p_confirmed_by,
    v_attempt_method,
    p_amount,
    v_attempt_status,
    p_idempotency_key,
    p_receipt_url,
    p_reference,
    p_bank_name,
    case when v_attempt_method = 'momo_online' then p_reference else null end,
    p_notes
  )
  returning id into v_attempt_id;

  -- 4) Neu chua auto-confirm thi dung o request layer, KHONG duoc cap nhat invoice.
  if not p_auto_confirm then
    return jsonb_build_object(
      'attemptId', v_attempt_id,
      'paymentId', null,
      'paymentCode', null,
      'attemptStatus', v_attempt_status,
      'invoiceId', p_invoice_id,
      'invoiceStatus', v_invoice.status,
      'amountPaid', v_invoice.amount_paid,
      'balanceDue', coalesce(v_invoice.balance_due, greatest(0, coalesce(v_invoice.total_amount, 0) - coalesce(v_invoice.amount_paid, 0)))
    );
  end if;

  -- 5) Nhung truong hop duoc auto-confirm (vi du admin thu cong co bang chung)
  --    se tao payment confirmed va apply dung 1 lan qua helper trung tam.
  insert into smartstay.payments (
    invoice_id,
    amount,
    method,
    bank_name,
    reference_number,
    receipt_url,
    payment_date,
    confirmed_by,
    confirmed_at,
    notes,
    status,
    payment_attempt_id
  )
  values (
    p_invoice_id,
    p_amount,
    smartstay.map_legacy_payment_method(v_attempt_method),
    p_bank_name,
    p_reference,
    p_receipt_url,
    coalesce(p_payment_date, now()),
    p_confirmed_by,
    now(),
    p_notes,
    'thanh_cong'::smartstay.payment_status,
    v_attempt_id
  )
  returning id, payment_code into v_payment_id, v_payment_code;

  update smartstay.payment_attempts
  set
    status = 'thanh_cong'::smartstay.payment_status,
    payment_id = v_payment_id,
    approved_at = now(),
    approved_by = p_confirmed_by
  where id = v_attempt_id;

  v_result := smartstay.apply_confirmed_payment(
    p_payment_id := v_payment_id,
    p_confirmation_source := case
      when v_attempt_method = 'tien_mat' then 'tien_mat'
      else 'admin_thu_cong'
    end,
    p_confirmed_by := p_confirmed_by,
    p_fail_if_applied := true
  );

  return v_result || jsonb_build_object(
    'attemptId', v_attempt_id,
    'paymentCode', v_payment_code,
    'attemptStatus', 'thanh_cong'
  );
end;
$$;

create or replace function smartstay.approve_payment(
  p_payment_id bigint,
  p_confirmed_by uuid default null,
  p_attempt_id bigint default null,
  p_confirmation_source text default 'admin_thu_cong'
)
returns jsonb
language plpgsql
security definer
set search_path = smartstay, public
as $$
declare
  v_attempt record;
  v_payment_id bigint;
  v_result jsonb;
begin
  -- Nhanh chinh cho model moi: approve tren payment_attempt.
  if p_attempt_id is not null then
    select
      pa.id,
      pa.invoice_id,
      pa.amount,
      pa.method,
      pa.status,
      pa.receipt_url,
      pa.reference_number,
      pa.bank_name,
      pa.notes,
      pa.payment_id
    into v_attempt
    from smartstay.payment_attempts pa
    where pa.id = p_attempt_id
    for update;

    if not found then
      raise exception 'Payment attempt not found: %', p_attempt_id;
    end if;

    if v_attempt.status in ('da_huy', 'bi_tu_choi', 'that_bai', 'da_hoan_tien') then
      raise exception 'Payment attempt % is not approvable in status %', p_attempt_id, v_attempt.status;
    end if;

    if v_attempt.payment_id is not null then
      raise exception 'Payment attempt % already created confirmed payment %', p_attempt_id, v_attempt.payment_id;
    end if;

    insert into smartstay.payments (
      invoice_id,
      amount,
      method,
      bank_name,
      reference_number,
      receipt_url,
      payment_date,
      confirmed_by,
      confirmed_at,
      notes,
      status,
      payment_attempt_id
    )
    values (
      v_attempt.invoice_id,
      v_attempt.amount,
      smartstay.map_legacy_payment_method(v_attempt.method),
      v_attempt.bank_name,
      v_attempt.reference_number,
      v_attempt.receipt_url,
      now(),
      p_confirmed_by,
      now(),
      v_attempt.notes,
      'thanh_cong'::smartstay.payment_status,
      v_attempt.id
    )
    returning id into v_payment_id;

    update smartstay.payment_attempts
    set
      status = 'thanh_cong'::smartstay.payment_status,
      payment_id = v_payment_id,
      approved_at = now(),
      approved_by = p_confirmed_by
    where id = v_attempt.id;

    return smartstay.apply_confirmed_payment(
      p_payment_id := v_payment_id,
      p_confirmation_source := p_confirmation_source,
      p_confirmed_by := p_confirmed_by,
      p_fail_if_applied := true
    );
  end if;

  -- Tuong thich nguoc: approve tren payments cu, nhung phai kiem tra applied_at de chan cong tien 2 lan.
  v_result := smartstay.apply_confirmed_payment(
    p_payment_id := p_payment_id,
    p_confirmation_source := p_confirmation_source,
    p_confirmed_by := p_confirmed_by,
    p_fail_if_applied := true
  );

  return v_result;
end;
$$;

create or replace function smartstay.adjust_balance(
  p_tenant_id bigint,
  p_amount numeric,
  p_transaction_type text,
  p_notes text,
  p_invoice_id bigint default null,
  p_created_by uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = smartstay, public
as $$
declare
  v_bal record;
  v_history_id bigint;
  v_after numeric;
begin
  perform smartstay.ensure_tenant_balance_record(p_tenant_id);

  select id, balance
  into v_bal
  from smartstay.tenant_balances
  where tenant_id = p_tenant_id
  for update;

  if not found then
    raise exception 'Tenant balance not found for tenant %', p_tenant_id;
  end if;

  v_after := coalesce(v_bal.balance, 0) + p_amount;

  insert into smartstay.balance_history (
    tenant_id,
    balance_id,
    transaction_type,
    amount,
    balance_before,
    balance_after,
    notes,
    invoice_id,
    created_by
  )
  values (
    p_tenant_id,
    v_bal.id,
    p_transaction_type::smartstay.balance_transaction_type,
    p_amount,
    coalesce(v_bal.balance, 0),
    v_after,
    p_notes,
    p_invoice_id,
    p_created_by
  )
  returning id into v_history_id;

  update smartstay.tenant_balances
  set balance = v_after, last_updated = now()
  where id = v_bal.id;

  return jsonb_build_object(
    'historyId', v_history_id,
    'balanceBefore', coalesce(v_bal.balance, 0),
    'balanceAfter', v_after
  );
end;
$$;

create or replace function smartstay.create_contract(
  p_room_id bigint,
  p_start_date date,
  p_end_date date,
  p_monthly_rent numeric,
  p_deposit_amount numeric,
  p_payment_cycle_months integer,
  p_tenant_ids bigint[],
  p_primary_tenant_id bigint,
  p_service_ids bigint[] default '{}'::bigint[],
  p_service_prices numeric[] default '{}'::numeric[],
  p_service_quantities integer[] default '{}'::integer[],
  p_mark_deposit_received boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = smartstay, public
as $$
declare
  v_contract_id bigint;
  v_contract_code text;
  v_tenant_id bigint;
  i integer;
begin
  if not exists (
    select 1
    from smartstay.rooms
    where id = p_room_id
      and status <> 'occupied'
  ) then
    raise exception 'Room % is not available (not found or already occupied)', p_room_id;
  end if;

  insert into smartstay.contracts (
    room_id,
    start_date,
    end_date,
    monthly_rent,
    deposit_amount,
    payment_cycle_months,
    status,
    deposit_status,
    is_deleted
  )
  values (
    p_room_id,
    p_start_date,
    p_end_date,
    p_monthly_rent,
    p_deposit_amount,
    p_payment_cycle_months,
    'active',
    case when p_mark_deposit_received then 'received' else 'pending' end,
    false
  )
  returning id, contract_code into v_contract_id, v_contract_code;

  foreach v_tenant_id in array p_tenant_ids loop
    insert into smartstay.contract_tenants (contract_id, tenant_id, is_primary)
    values (v_contract_id, v_tenant_id, v_tenant_id = p_primary_tenant_id);
  end loop;

  if array_length(p_service_ids, 1) is not null then
    for i in 1..array_length(p_service_ids, 1) loop
      insert into smartstay.contract_services (contract_id, service_id, fixed_price, quantity)
      values (
        v_contract_id,
        p_service_ids[i],
        case when array_length(p_service_prices, 1) >= i then p_service_prices[i] else null end,
        case when array_length(p_service_quantities, 1) >= i then p_service_quantities[i] else 1 end
      );
    end loop;
  end if;

  update smartstay.rooms
  set status = 'occupied'
  where id = p_room_id;

  return jsonb_build_object(
    'contractId', v_contract_id,
    'contractCode', v_contract_code
  );
end;
$$;

create or replace function smartstay.handle_momo_ipn(
  p_payload jsonb,
  p_secret_key text,
  p_access_key text,
  p_received_at timestamptz default now()
)
returns jsonb
language plpgsql
security definer
set search_path = smartstay, public
as $$
declare
  v_log_id bigint;
  v_order_id text;
  v_request_id text;
  v_trans_id text;
  v_message text;
  v_signature text;
  v_raw_signature text;
  v_expected_signature text;
  v_result_code integer;
  v_amount numeric;
  v_attempt record;
  v_result jsonb;
begin
  insert into smartstay.webhook_logs (
    provider,
    payload,
    received_at,
    status
  )
  values (
    'momo',
    coalesce(p_payload, '{}'::jsonb),
    coalesce(p_received_at, now()),
    'processing'
  )
  returning id into v_log_id;

  v_order_id := nullif(p_payload ->> 'orderId', '');
  v_request_id := nullif(p_payload ->> 'requestId', '');
  v_trans_id := nullif(p_payload ->> 'transId', '');
  v_message := coalesce(p_payload ->> 'message', '');
  v_signature := lower(coalesce(p_payload ->> 'signature', ''));
  v_result_code := coalesce(nullif(p_payload ->> 'resultCode', '')::integer, -1);
  v_amount := coalesce(nullif(p_payload ->> 'amount', '')::numeric, 0);

  v_raw_signature := format(
    'accessKey=%s&amount=%s&extraData=%s&message=%s&orderId=%s&orderInfo=%s&orderType=%s&partnerCode=%s&payType=%s&requestId=%s&responseTime=%s&resultCode=%s&transId=%s',
    coalesce(p_access_key, ''),
    coalesce(p_payload ->> 'amount', ''),
    coalesce(p_payload ->> 'extraData', ''),
    coalesce(p_payload ->> 'message', ''),
    coalesce(v_order_id, ''),
    coalesce(p_payload ->> 'orderInfo', ''),
    coalesce(p_payload ->> 'orderType', ''),
    coalesce(p_payload ->> 'partnerCode', ''),
    coalesce(p_payload ->> 'payType', ''),
    coalesce(v_request_id, ''),
    coalesce(p_payload ->> 'responseTime', ''),
    coalesce(p_payload ->> 'resultCode', ''),
    coalesce(v_trans_id, '')
  );

  v_expected_signature := lower(
    encode(
      extensions.hmac(v_raw_signature::bytea, coalesce(p_secret_key, '')::bytea, 'sha256'),
      'hex'
    )
  );

  if v_signature = '' or v_expected_signature <> v_signature then
    update smartstay.webhook_logs
    set
      status = 'failed',
      error_message = 'invalid_signature',
      processed_at = now()
    where id = v_log_id;

    return jsonb_build_object('status', 'invalid_signature');
  end if;

  select
    pa.id,
    pa.invoice_id,
    pa.amount,
    pa.status,
    pa.payment_id
  into v_attempt
  from smartstay.payment_attempts pa
  where pa.gateway_order_id = v_order_id
     or pa.idempotency_key = concat('momo:', v_order_id)
  order by pa.id desc
  limit 1
  for update;

  if not found then
    update smartstay.webhook_logs
    set
      status = 'failed',
      error_message = 'payment_attempt_not_found',
      processed_at = now()
    where id = v_log_id;

    return jsonb_build_object('status', 'payment_attempt_not_found', 'orderId', v_order_id);
  end if;

  if v_attempt.payment_id is not null or v_attempt.status = 'thanh_cong' then
    update smartstay.payment_attempts
    set
      status = 'thanh_cong'::smartstay.payment_status,
      gateway_request_id = coalesce(v_request_id, gateway_request_id),
      gateway_transaction_id = coalesce(v_trans_id, gateway_transaction_id),
      gateway_payload = coalesce(p_payload, '{}'::jsonb)
    where id = v_attempt.id;

    update smartstay.webhook_logs
    set
      status = 'success',
      processed_at = now(),
      error_message = null
    where id = v_log_id;

    return jsonb_build_object('status', 'duplicate', 'attemptId', v_attempt.id, 'paymentId', v_attempt.payment_id);
  end if;

  if v_result_code <> 0 then
    update smartstay.payment_attempts
    set
      status = 'that_bai'::smartstay.payment_status,
      gateway_request_id = coalesce(v_request_id, gateway_request_id),
      gateway_transaction_id = coalesce(v_trans_id, gateway_transaction_id),
      gateway_payload = coalesce(p_payload, '{}'::jsonb),
      notes = concat_ws(E'\n', notes, format('[momo_ipn] %s', v_message))
    where id = v_attempt.id;

    update smartstay.webhook_logs
    set
      status = 'failed',
      error_message = format('momo_result_code_%s', v_result_code),
      processed_at = now()
    where id = v_log_id;

    return jsonb_build_object('status', 'payment_failed', 'attemptId', v_attempt.id, 'resultCode', v_result_code);
  end if;

  if v_amount <> v_attempt.amount then
    update smartstay.webhook_logs
    set
      status = 'failed',
      error_message = 'amount_mismatch',
      processed_at = now()
    where id = v_log_id;

    raise exception 'MoMo IPN amount mismatch for attempt %', v_attempt.id;
  end if;

  update smartstay.payment_attempts
  set
    status = 'dang_xu_ly'::smartstay.payment_status,
    gateway_request_id = coalesce(v_request_id, gateway_request_id),
    gateway_transaction_id = coalesce(v_trans_id, gateway_transaction_id),
    gateway_payload = coalesce(p_payload, '{}'::jsonb)
  where id = v_attempt.id;

  v_result := smartstay.approve_payment(
    p_payment_id := 0,
    p_confirmed_by := null,
    p_attempt_id := v_attempt.id,
    p_confirmation_source := 'momo_ipn'
  );

  update smartstay.webhook_logs
  set
    status = 'success',
    error_message = null,
    processed_at = now()
  where id = v_log_id;

  return v_result || jsonb_build_object(
    'status', 'processed',
    'attemptId', v_attempt.id,
    'provider', 'momo'
  );
exception
  when others then
    update smartstay.webhook_logs
    set
      status = 'failed',
      error_message = sqlerrm,
      processed_at = now()
    where id = v_log_id;

    raise;
end;
$$;

create or replace function smartstay.portal_record_invoice_payment(
  p_invoice_id bigint,
  p_amount numeric,
  p_method text,
  p_payment_date timestamp with time zone,
  p_notes text default null,
  p_reference text default null,
  p_bank_name text default null
)
returns jsonb
language plpgsql
security definer
set search_path = smartstay, public
as $$
declare
  v_actor_id uuid := auth.uid();
  v_invoice record;
  v_attempt_status smartstay.payment_status;
begin
  if v_actor_id is null then
    raise exception 'Authentication required';
  end if;

  select
    i.id,
    i.contract_id,
    i.amount_paid,
    i.balance_due,
    i.total_amount,
    i.status
  into v_invoice
  from smartstay.invoices i
  where i.id = p_invoice_id
    and exists (
      select 1
      from smartstay.contract_tenants ct
      join smartstay.tenants t on t.id = ct.tenant_id
      where ct.contract_id = i.contract_id
        and t.profile_id = v_actor_id
        and coalesce(t.is_deleted, false) = false
    )
  for update;

  if not found then
    raise exception 'Invoice not found or access denied';
  end if;

  if smartstay.map_payment_attempt_method(p_method) = 'momo_online'::smartstay.payment_attempt_method then
    v_attempt_status := 'cho_xu_ly'::smartstay.payment_status;
  else
    v_attempt_status := 'da_gui'::smartstay.payment_status;
  end if;

  return smartstay.process_payment(
    p_invoice_id := p_invoice_id,
    p_amount := p_amount,
    p_method := p_method,
    p_payment_date := p_payment_date,
    p_notes := p_notes,
    p_receipt_url := null,
    p_reference := p_reference,
    p_bank_name := p_bank_name,
    p_confirmed_by := v_actor_id,
    p_auto_confirm := false,
    p_idempotency_key := case
      when p_reference is not null and smartstay.map_payment_attempt_method(p_method) = 'momo_online'::smartstay.payment_attempt_method
        then concat('momo:', p_reference)
      else null
    end,
    p_attempt_status := v_attempt_status
  );
end;
$$;

update smartstay.payments
set
  status = case
    when confirmed_at is not null then 'thanh_cong'::smartstay.payment_status
    else 'cho_xu_ly'::smartstay.payment_status
  end,
  confirmation_source = case
    when confirmed_at is not null and method = 'momo'::smartstay.payment_method then coalesce(confirmation_source, 'momo_ipn')
    when confirmed_at is not null and method = 'cash'::smartstay.payment_method then coalesce(confirmation_source, 'tien_mat')
    when confirmed_at is not null then coalesce(confirmation_source, 'admin_thu_cong')
    else confirmation_source
  end,
  applied_at = case
    when confirmed_at is not null then coalesce(applied_at, confirmed_at, payment_date, created_at, now())
    else null
  end
where status is null
   or applied_at is null
   or confirmation_source is null;

alter table smartstay.payments
  alter column status set default 'cho_xu_ly',
  alter column status set not null;

insert into smartstay.tenant_balances (tenant_id, balance, last_updated)
select distinct
  ct.tenant_id,
  0,
  now()
from smartstay.contract_tenants ct
left join smartstay.tenant_balances tb on tb.tenant_id = ct.tenant_id
where tb.tenant_id is null;

with payment_rollup as (
  select
    p.invoice_id,
    sum(
      case
        when p.status = 'thanh_cong'::smartstay.payment_status then p.amount
        else 0
      end
    ) as confirmed_amount,
    max(
      case
        when p.status = 'thanh_cong'::smartstay.payment_status then coalesce(p.applied_at, p.confirmed_at, p.payment_date, p.created_at)
        else null
      end
    ) as last_confirmed_at
  from smartstay.payments p
  group by p.invoice_id
)
update smartstay.invoices i
set
  amount_paid = coalesce(pr.confirmed_amount, 0),
  status = case
    when i.status = 'cancelled'::smartstay.invoice_status then 'cancelled'::smartstay.invoice_status
    when coalesce(pr.confirmed_amount, 0) >= coalesce(i.total_amount, 0) and coalesce(i.total_amount, 0) > 0 then 'paid'::smartstay.invoice_status
    when coalesce(pr.confirmed_amount, 0) > 0 then 'partially_paid'::smartstay.invoice_status
    when i.status = 'draft'::smartstay.invoice_status then 'draft'::smartstay.invoice_status
    when i.due_date is not null and i.due_date < current_date then 'overdue'::smartstay.invoice_status
    else 'pending_payment'::smartstay.invoice_status
  end,
  paid_date = case
    when coalesce(pr.confirmed_amount, 0) >= coalesce(i.total_amount, 0) and coalesce(i.total_amount, 0) > 0 then coalesce(pr.last_confirmed_at, i.paid_date, now())
    else null
  end,
  updated_at = now()
from payment_rollup pr
where pr.invoice_id = i.id
  and (
    coalesce(i.amount_paid, 0) <> coalesce(pr.confirmed_amount, 0)
    or coalesce(i.amount_paid, 0) > coalesce(i.total_amount, 0)
  );

commit;
