begin;

do $$
begin
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'smartstay'
      and t.typname = 'utility_policy_scope'
  ) then
    create type smartstay.utility_policy_scope as enum (
      'system',
      'building',
      'room',
      'contract'
    );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'smartstay'
      and t.typname = 'billing_run_status'
  ) then
    create type smartstay.billing_run_status as enum (
      'draft',
      'running',
      'completed',
      'failed',
      'cancelled'
    );
  end if;
end
$$;

create or replace function smartstay.touch_utility_updated_at()
returns trigger
language plpgsql
set search_path = smartstay, public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create table if not exists smartstay.utility_policies (
  id bigint generated by default as identity primary key,
  code text not null,
  name text not null,
  scope_type smartstay.utility_policy_scope not null,
  scope_id bigint null,
  is_active boolean not null default true,
  description text null,
  electric_base_amount numeric not null default 0 check (electric_base_amount >= 0),
  water_base_amount numeric not null default 0 check (water_base_amount >= 0),
  water_per_person_amount numeric not null default 0 check (water_per_person_amount >= 0),
  electric_hot_season_multiplier numeric not null default 1.15 check (electric_hot_season_multiplier > 0),
  location_multiplier numeric not null default 1.0 check (location_multiplier > 0),
  season_months jsonb not null default '["04","05","06","07","08","09"]'::jsonb,
  rounding_increment numeric not null default 1000 check (rounding_increment > 0),
  min_electric_floor numeric not null default 120000 check (min_electric_floor >= 0),
  min_water_floor numeric not null default 60000 check (min_water_floor >= 0),
  effective_from date not null default current_date,
  effective_to date null,
  created_by uuid null references smartstay.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint utility_policies_scope_ck check (
    (scope_type = 'system' and scope_id is null)
    or (scope_type <> 'system' and scope_id is not null)
  ),
  constraint utility_policies_effective_range_ck check (
    effective_to is null or effective_to >= effective_from
  ),
  constraint utility_policies_season_months_ck check (
    jsonb_typeof(season_months) = 'array'
  ),
  constraint utility_policies_code_key unique (code)
);

comment on table smartstay.utility_policies is 'Policy utility billing theo scope system/building/room/contract cho mo hinh khong cong to.';
comment on column smartstay.utility_policies.scope_type is 'Thu tu resolve duoc ap o service layer: invoice-period override -> contract -> room -> building -> system.';
comment on column smartstay.utility_policies.season_months is 'Danh sach thang nong dang string MM. Neu thang billing nam trong danh sach nay thi ap electric_hot_season_multiplier, nguoc lai mac dinh multiplier = 1.0.';
comment on column smartstay.utility_policies.rounding_increment is 'Muc lam tron canonical cho utility. Ban dau la 1000 VND.';

create index if not exists utility_policies_scope_active_idx
  on smartstay.utility_policies (scope_type, scope_id, is_active, effective_from desc);

create index if not exists utility_policies_effective_period_idx
  on smartstay.utility_policies (effective_from desc, effective_to);

create table if not exists smartstay.utility_policy_device_adjustments (
  id bigint generated by default as identity primary key,
  utility_policy_id bigint not null references smartstay.utility_policies(id) on delete cascade,
  device_code text not null,
  charge_amount numeric not null default 0 check (charge_amount >= 0),
  is_active boolean not null default true,
  notes text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint utility_policy_device_adjustments_unique_device unique (utility_policy_id, device_code)
);

comment on table smartstay.utility_policy_device_adjustments is 'Phu thu thiet bi cho tien dien. Device inventory cua phong se duoc resolve o lop nghiep vu tu metadata phong hien co.';
comment on column smartstay.utility_policy_device_adjustments.device_code is 'Vi du: aircon, electric_stove, water_heater, dryer, freezer.';

create index if not exists utility_policy_device_adjustments_policy_idx
  on smartstay.utility_policy_device_adjustments (utility_policy_id, is_active);

create table if not exists smartstay.billing_runs (
  id bigint generated by default as identity primary key,
  billing_period text not null,
  status smartstay.billing_run_status not null default 'draft',
  started_at timestamptz null,
  completed_at timestamptz null,
  created_by uuid null references smartstay.profiles(id),
  lock_version integer not null default 0,
  summary_json jsonb not null default '{}'::jsonb,
  error_json jsonb not null default '{}'::jsonb,
  notes text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint billing_runs_billing_period_ck check (billing_period ~ '^\d{4}-\d{2}$'),
  constraint billing_runs_completed_after_started_ck check (
    completed_at is null or started_at is null or completed_at >= started_at
  ),
  constraint billing_runs_billing_period_key unique (billing_period)
);

comment on table smartstay.billing_runs is 'Moi ky billing dau thang chi co 1 run canonical. Retry phai cap nhat cung row de giu idempotency.';
comment on column smartstay.billing_runs.lock_version is 'Dung cho optimistic concurrency khi co nhieu admin thao tac cung billing run.';

create index if not exists billing_runs_status_idx
  on smartstay.billing_runs (status, created_at desc);

create table if not exists smartstay.invoice_utility_overrides (
  id bigint generated by default as identity primary key,
  contract_id integer not null references smartstay.contracts(id) on delete cascade,
  invoice_id integer null references smartstay.invoices(id) on delete set null,
  billing_period text not null,
  occupants_for_billing_override integer null check (occupants_for_billing_override >= 0),
  electric_base_override numeric null check (electric_base_override >= 0),
  electric_final_override numeric null check (electric_final_override >= 0),
  water_base_override numeric null check (water_base_override >= 0),
  water_final_override numeric null check (water_final_override >= 0),
  location_multiplier_override numeric null check (location_multiplier_override > 0),
  season_months_override jsonb null,
  electric_hot_season_multiplier_override numeric null check (electric_hot_season_multiplier_override > 0),
  reason text not null,
  old_values_json jsonb not null default '{}'::jsonb,
  new_values_json jsonb not null default '{}'::jsonb,
  created_by uuid null references smartstay.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint invoice_utility_overrides_period_ck check (billing_period ~ '^\d{4}-\d{2}$'),
  constraint invoice_utility_overrides_season_months_ck check (
    season_months_override is null or jsonb_typeof(season_months_override) = 'array'
  ),
  constraint invoice_utility_overrides_key unique (contract_id, billing_period)
);

comment on table smartstay.invoice_utility_overrides is 'Override utility cho duy nhat 1 ky billing. Khong duoc dung de sua policy goc.';
comment on column smartstay.invoice_utility_overrides.old_values_json is 'Snapshot gia tri resolve truoc khi admin sua.';
comment on column smartstay.invoice_utility_overrides.new_values_json is 'Gia tri sau override de audit va replay.';

create index if not exists invoice_utility_overrides_invoice_idx
  on smartstay.invoice_utility_overrides (invoice_id);

create index if not exists invoice_utility_overrides_period_idx
  on smartstay.invoice_utility_overrides (billing_period, created_at desc);

create table if not exists smartstay.invoice_utility_snapshots (
  id bigint generated by default as identity primary key,
  invoice_id integer not null references smartstay.invoices(id) on delete cascade,
  contract_id integer not null references smartstay.contracts(id) on delete cascade,
  room_id integer not null references smartstay.rooms(id) on delete restrict,
  billing_run_id bigint null references smartstay.billing_runs(id) on delete set null,
  override_id bigint null references smartstay.invoice_utility_overrides(id) on delete set null,
  resolved_policy_id bigint null references smartstay.utility_policies(id) on delete set null,
  billing_period text not null,
  period_start date not null,
  period_end date not null,
  policy_source_type text not null,
  occupants_for_billing integer not null check (occupants_for_billing >= 0),
  occupied_days integer not null check (occupied_days >= 0),
  days_in_period integer not null check (days_in_period > 0),
  prorate_ratio numeric not null check (prorate_ratio >= 0 and prorate_ratio <= 1),
  electric_base_amount numeric not null default 0 check (electric_base_amount >= 0),
  electric_device_surcharge numeric not null default 0 check (electric_device_surcharge >= 0),
  electric_subtotal numeric not null default 0 check (electric_subtotal >= 0),
  electric_season_multiplier numeric not null default 1.0 check (electric_season_multiplier > 0),
  electric_location_multiplier numeric not null default 1.0 check (electric_location_multiplier > 0),
  electric_raw_amount numeric not null default 0 check (electric_raw_amount >= 0),
  electric_rounded_amount numeric not null default 0 check (electric_rounded_amount >= 0),
  min_electric_floor numeric not null default 0 check (min_electric_floor >= 0),
  electric_final_amount numeric not null default 0 check (electric_final_amount >= 0),
  water_base_amount numeric not null default 0 check (water_base_amount >= 0),
  water_per_person_amount numeric not null default 0 check (water_per_person_amount >= 0),
  water_person_charge numeric not null default 0 check (water_person_charge >= 0),
  water_subtotal numeric not null default 0 check (water_subtotal >= 0),
  water_location_multiplier numeric not null default 1.0 check (water_location_multiplier > 0),
  water_raw_amount numeric not null default 0 check (water_raw_amount >= 0),
  water_rounded_amount numeric not null default 0 check (water_rounded_amount >= 0),
  min_water_floor numeric not null default 0 check (min_water_floor >= 0),
  water_final_amount numeric not null default 0 check (water_final_amount >= 0),
  rounding_increment numeric not null default 1000 check (rounding_increment > 0),
  resolved_device_surcharges_json jsonb not null default '[]'::jsonb,
  warnings_json jsonb not null default '[]'::jsonb,
  formula_snapshot_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint invoice_utility_snapshots_billing_period_ck check (billing_period ~ '^\d{4}-\d{2}$'),
  constraint invoice_utility_snapshots_period_ck check (period_end >= period_start),
  constraint invoice_utility_snapshots_invoice_key unique (invoice_id)
);

comment on table smartstay.invoice_utility_snapshots is 'Immutable snapshot cong thuc utility tai thoi diem tao invoice.';
comment on column smartstay.invoice_utility_snapshots.policy_source_type is 'Gia tri ky vong: invoice_override, contract, room, building, system.';
comment on column smartstay.invoice_utility_snapshots.resolved_device_surcharges_json is 'Danh sach phu thu thiet bi da resolve, vi du [{\"device_code\":\"aircon\",\"charge_amount\":25000}].';
comment on column smartstay.invoice_utility_snapshots.warnings_json is 'Danh sach warning business guard, vi du duoi floor truoc khi ap floor.';
comment on column smartstay.invoice_utility_snapshots.formula_snapshot_json is 'Snapshot day du cua cong thuc va input da dung de tinh utility.';

create index if not exists invoice_utility_snapshots_contract_period_idx
  on smartstay.invoice_utility_snapshots (contract_id, billing_period);

create index if not exists invoice_utility_snapshots_room_period_idx
  on smartstay.invoice_utility_snapshots (room_id, billing_period);

drop trigger if exists trg_touch_utility_policies_updated_at on smartstay.utility_policies;
create trigger trg_touch_utility_policies_updated_at
before update on smartstay.utility_policies
for each row
execute function smartstay.touch_utility_updated_at();

drop trigger if exists trg_touch_utility_policy_device_adjustments_updated_at on smartstay.utility_policy_device_adjustments;
create trigger trg_touch_utility_policy_device_adjustments_updated_at
before update on smartstay.utility_policy_device_adjustments
for each row
execute function smartstay.touch_utility_updated_at();

drop trigger if exists trg_touch_billing_runs_updated_at on smartstay.billing_runs;
create trigger trg_touch_billing_runs_updated_at
before update on smartstay.billing_runs
for each row
execute function smartstay.touch_utility_updated_at();

drop trigger if exists trg_touch_invoice_utility_overrides_updated_at on smartstay.invoice_utility_overrides;
create trigger trg_touch_invoice_utility_overrides_updated_at
before update on smartstay.invoice_utility_overrides
for each row
execute function smartstay.touch_utility_updated_at();

alter table smartstay.utility_policies enable row level security;
alter table smartstay.utility_policies force row level security;

alter table smartstay.utility_policy_device_adjustments enable row level security;
alter table smartstay.utility_policy_device_adjustments force row level security;

alter table smartstay.billing_runs enable row level security;
alter table smartstay.billing_runs force row level security;

alter table smartstay.invoice_utility_overrides enable row level security;
alter table smartstay.invoice_utility_overrides force row level security;

alter table smartstay.invoice_utility_snapshots enable row level security;
alter table smartstay.invoice_utility_snapshots force row level security;

drop policy if exists utility_policies_admin_select on smartstay.utility_policies;
create policy utility_policies_admin_select
on smartstay.utility_policies
for select
to authenticated
using ((select private.is_admin((select auth.uid()))));

drop policy if exists utility_policies_admin_insert on smartstay.utility_policies;
create policy utility_policies_admin_insert
on smartstay.utility_policies
for insert
to authenticated
with check ((select private.is_admin((select auth.uid()))));

drop policy if exists utility_policies_admin_update on smartstay.utility_policies;
create policy utility_policies_admin_update
on smartstay.utility_policies
for update
to authenticated
using ((select private.is_admin((select auth.uid()))))
with check ((select private.is_admin((select auth.uid()))));

drop policy if exists utility_policies_admin_delete on smartstay.utility_policies;
create policy utility_policies_admin_delete
on smartstay.utility_policies
for delete
to authenticated
using ((select private.is_admin((select auth.uid()))));

drop policy if exists utility_policy_device_adjustments_admin_select on smartstay.utility_policy_device_adjustments;
create policy utility_policy_device_adjustments_admin_select
on smartstay.utility_policy_device_adjustments
for select
to authenticated
using ((select private.is_admin((select auth.uid()))));

drop policy if exists utility_policy_device_adjustments_admin_insert on smartstay.utility_policy_device_adjustments;
create policy utility_policy_device_adjustments_admin_insert
on smartstay.utility_policy_device_adjustments
for insert
to authenticated
with check ((select private.is_admin((select auth.uid()))));

drop policy if exists utility_policy_device_adjustments_admin_update on smartstay.utility_policy_device_adjustments;
create policy utility_policy_device_adjustments_admin_update
on smartstay.utility_policy_device_adjustments
for update
to authenticated
using ((select private.is_admin((select auth.uid()))))
with check ((select private.is_admin((select auth.uid()))));

drop policy if exists utility_policy_device_adjustments_admin_delete on smartstay.utility_policy_device_adjustments;
create policy utility_policy_device_adjustments_admin_delete
on smartstay.utility_policy_device_adjustments
for delete
to authenticated
using ((select private.is_admin((select auth.uid()))));

drop policy if exists billing_runs_admin_select on smartstay.billing_runs;
create policy billing_runs_admin_select
on smartstay.billing_runs
for select
to authenticated
using ((select private.is_admin((select auth.uid()))));

drop policy if exists billing_runs_admin_insert on smartstay.billing_runs;
create policy billing_runs_admin_insert
on smartstay.billing_runs
for insert
to authenticated
with check ((select private.is_admin((select auth.uid()))));

drop policy if exists billing_runs_admin_update on smartstay.billing_runs;
create policy billing_runs_admin_update
on smartstay.billing_runs
for update
to authenticated
using ((select private.is_admin((select auth.uid()))))
with check ((select private.is_admin((select auth.uid()))));

drop policy if exists billing_runs_admin_delete on smartstay.billing_runs;
create policy billing_runs_admin_delete
on smartstay.billing_runs
for delete
to authenticated
using ((select private.is_admin((select auth.uid()))));

drop policy if exists invoice_utility_overrides_admin_select on smartstay.invoice_utility_overrides;
create policy invoice_utility_overrides_admin_select
on smartstay.invoice_utility_overrides
for select
to authenticated
using ((select private.is_admin((select auth.uid()))));

drop policy if exists invoice_utility_overrides_admin_insert on smartstay.invoice_utility_overrides;
create policy invoice_utility_overrides_admin_insert
on smartstay.invoice_utility_overrides
for insert
to authenticated
with check ((select private.is_admin((select auth.uid()))));

drop policy if exists invoice_utility_overrides_admin_update on smartstay.invoice_utility_overrides;
create policy invoice_utility_overrides_admin_update
on smartstay.invoice_utility_overrides
for update
to authenticated
using ((select private.is_admin((select auth.uid()))))
with check ((select private.is_admin((select auth.uid()))));

drop policy if exists invoice_utility_overrides_admin_delete on smartstay.invoice_utility_overrides;
create policy invoice_utility_overrides_admin_delete
on smartstay.invoice_utility_overrides
for delete
to authenticated
using ((select private.is_admin((select auth.uid()))));

drop policy if exists invoice_utility_snapshots_owner_or_admin_select on smartstay.invoice_utility_snapshots;
create policy invoice_utility_snapshots_owner_or_admin_select
on smartstay.invoice_utility_snapshots
for select
to authenticated
using (
  (select private.is_admin((select auth.uid())))
  or (select private.is_invoice_owner(invoice_id, (select auth.uid())))
);

drop policy if exists invoice_utility_snapshots_admin_insert on smartstay.invoice_utility_snapshots;
create policy invoice_utility_snapshots_admin_insert
on smartstay.invoice_utility_snapshots
for insert
to authenticated
with check ((select private.is_admin((select auth.uid()))));

drop policy if exists invoice_utility_snapshots_admin_update on smartstay.invoice_utility_snapshots;
create policy invoice_utility_snapshots_admin_update
on smartstay.invoice_utility_snapshots
for update
to authenticated
using ((select private.is_admin((select auth.uid()))))
with check ((select private.is_admin((select auth.uid()))));

drop policy if exists invoice_utility_snapshots_admin_delete on smartstay.invoice_utility_snapshots;
create policy invoice_utility_snapshots_admin_delete
on smartstay.invoice_utility_snapshots
for delete
to authenticated
using ((select private.is_admin((select auth.uid()))));

commit;
