set search_path = smartstay, public;

create table if not exists smartstay.room_images (
  id          bigint generated by default as identity primary key,
  room_id     bigint not null references smartstay.rooms(id) on delete cascade,
  url         text   not null,
  is_main     boolean not null default false,
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now()
);

-- Only one image can be main per room
create unique index if not exists room_images_main_idx
  on smartstay.room_images (room_id)
  where is_main = true;

-- RLS
alter table smartstay.room_images enable row level security;

create policy "Public read room images"
  on smartstay.room_images for select
  using (true);

create policy "Authenticated insert room images"
  on smartstay.room_images for insert
  to authenticated
  with check (true);

create policy "Authenticated delete room images"
  on smartstay.room_images for delete
  to authenticated
  using (true);

create policy "Authenticated update room images"
  on smartstay.room_images for update
  to authenticated
  using (true);
