set search_path = smartstay, public;

create table if not exists smartstay.building_images (
  id          bigint generated by default as identity primary key,
  building_id bigint not null references smartstay.buildings(id) on delete cascade,
  url         text   not null,
  is_main     boolean not null default false,
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now()
);

-- Only one image can be main per building
create unique index if not exists building_images_main_idx
  on smartstay.building_images (building_id)
  where is_main = true;

-- RLS
alter table smartstay.building_images enable row level security;

create policy "Public read building images"
  on smartstay.building_images for select
  using (true);

create policy "Authenticated insert building images"
  on smartstay.building_images for insert
  to authenticated
  with check (true);

create policy "Authenticated delete building images"
  on smartstay.building_images for delete
  to authenticated
  using (true);

create policy "Authenticated update building images"
  on smartstay.building_images for update
  to authenticated
  using (true);
