create type smartstay.occupant_status as enum ('active', 'moved_out');

create type smartstay.contract_transfer_status as enum ('pending', 'completed', 'cancelled');

alter table smartstay.contracts
  add column if not exists primary_tenant_id integer,
  add column if not exists linked_contract_id integer,
  add column if not exists payment_due_day smallint not null default 5,
  add column if not exists notice_period_days integer not null default 30,
  add column if not exists deposit_note text,
  add column if not exists signed_at timestamptz,
  add column if not exists signed_file_url text,
  add column if not exists created_by uuid,
  add column if not exists approved_by uuid,
  add column if not exists terminated_at timestamptz;

alter table smartstay.contracts
  add constraint contracts_primary_tenant_id_fkey
    foreign key (primary_tenant_id) references smartstay.tenants(id) on delete restrict;

alter table smartstay.contracts
  add constraint contracts_linked_contract_id_fkey
    foreign key (linked_contract_id) references smartstay.contracts(id) on delete set null;

alter table smartstay.contracts
  add constraint contracts_created_by_fkey
    foreign key (created_by) references smartstay.profiles(id) on delete set null;

alter table smartstay.contracts
  add constraint contracts_approved_by_fkey
    foreign key (approved_by) references smartstay.profiles(id) on delete set null;

alter table smartstay.contracts
  add constraint contracts_payment_due_day_check
    check (payment_due_day between 1 and 31);

alter table smartstay.contracts
  add constraint contracts_notice_period_days_check
    check (notice_period_days >= 0);

create index if not exists idx_contracts_primary_tenant on smartstay.contracts(primary_tenant_id);
create index if not exists idx_contracts_linked_contract on smartstay.contracts(linked_contract_id);
create index if not exists idx_contracts_created_by on smartstay.contracts(created_by);
create index if not exists idx_contracts_approved_by on smartstay.contracts(approved_by);

update smartstay.contracts c
set primary_tenant_id = src.tenant_id
from (
  select distinct on (ct.contract_id)
    ct.contract_id,
    ct.tenant_id
  from smartstay.contract_tenants ct
  order by ct.contract_id, ct.is_primary desc, ct.id asc
) src
where c.id = src.contract_id
  and c.primary_tenant_id is null;

create table if not exists smartstay.room_occupants (
  id bigint generated by default as identity primary key,
  contract_id integer not null references smartstay.contracts(id) on delete cascade,
  room_id integer not null references smartstay.rooms(id) on delete restrict,
  tenant_id integer not null references smartstay.tenants(id) on delete restrict,
  is_primary_tenant boolean not null default false,
  relationship_to_primary text,
  note text,
  move_in_at date not null,
  move_out_at date,
  status smartstay.occupant_status not null default 'active',
  created_by uuid references smartstay.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint room_occupants_unique_contract_tenant unique (contract_id, tenant_id),
  constraint room_occupants_move_out_check check (move_out_at is null or move_out_at >= move_in_at),
  constraint room_occupants_status_check check (
    (status = 'active' and move_out_at is null)
    or (status = 'moved_out' and move_out_at is not null)
  )
);

create unique index if not exists idx_room_occupants_active_primary
  on smartstay.room_occupants(contract_id)
  where status = 'active' and is_primary_tenant = true;

create index if not exists idx_room_occupants_contract_status
  on smartstay.room_occupants(contract_id, status);

create index if not exists idx_room_occupants_room_status
  on smartstay.room_occupants(room_id, status);

create index if not exists idx_room_occupants_tenant_status
  on smartstay.room_occupants(tenant_id, status);

insert into smartstay.room_occupants (
  contract_id,
  room_id,
  tenant_id,
  is_primary_tenant,
  move_in_at,
  move_out_at,
  status
)
select
  ct.contract_id,
  c.room_id,
  ct.tenant_id,
  coalesce(ct.is_primary, false),
  c.start_date,
  case
    when c.status in ('active', 'pending_signature') and coalesce(c.is_deleted, false) = false then null
    else c.end_date
  end,
  case
    when c.status in ('active', 'pending_signature') and coalesce(c.is_deleted, false) = false then 'active'::smartstay.occupant_status
    else 'moved_out'::smartstay.occupant_status
  end
from smartstay.contract_tenants ct
join smartstay.contracts c on c.id = ct.contract_id
on conflict (contract_id, tenant_id) do nothing;

create table if not exists smartstay.contract_transfers (
  id bigint generated by default as identity primary key,
  old_contract_id integer not null references smartstay.contracts(id) on delete restrict,
  new_contract_id integer not null references smartstay.contracts(id) on delete restrict,
  room_id integer not null references smartstay.rooms(id) on delete restrict,
  from_tenant_id integer not null references smartstay.tenants(id) on delete restrict,
  to_tenant_id integer not null references smartstay.tenants(id) on delete restrict,
  transfer_date date not null,
  approved_by uuid references smartstay.profiles(id),
  status smartstay.contract_transfer_status not null default 'completed',
  deposit_mode text not null default 'carry_over',
  carry_over_deposit_amount numeric(12,2) not null default 0,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint contract_transfers_old_new_unique unique (old_contract_id, new_contract_id),
  constraint contract_transfers_deposit_amount_check check (carry_over_deposit_amount >= 0)
);

create index if not exists idx_contract_transfers_old_contract
  on smartstay.contract_transfers(old_contract_id);

create index if not exists idx_contract_transfers_new_contract
  on smartstay.contract_transfers(new_contract_id);

create index if not exists idx_contract_transfers_room_date
  on smartstay.contract_transfers(room_id, transfer_date desc);

create table if not exists smartstay.contract_addendums (
  id bigint generated by default as identity primary key,
  contract_id integer not null references smartstay.contracts(id) on delete cascade,
  addendum_code text generated always as ('PL-' || lpad(id::text, 6, '0')) stored,
  title text not null,
  content text,
  effective_date date not null,
  status text not null default 'draft',
  signed_file_url text,
  created_by uuid references smartstay.profiles(id) on delete set null,
  approved_by uuid references smartstay.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint contract_addendums_status_check check (status in ('draft', 'signed', 'cancelled'))
);

create index if not exists idx_contract_addendums_contract
  on smartstay.contract_addendums(contract_id, effective_date desc);

alter table smartstay.room_occupants enable row level security;
alter table smartstay.contract_transfers enable row level security;
alter table smartstay.contract_addendums enable row level security;

create policy authenticated_select_room_occupants
  on smartstay.room_occupants
  for select
  to authenticated
  using (true);

create policy admin_all_room_occupants
  on smartstay.room_occupants
  to authenticated
  using ((select private.is_admin((select auth.uid()))))
  with check ((select private.is_admin((select auth.uid()))));

create policy authenticated_select_contract_transfers
  on smartstay.contract_transfers
  for select
  to authenticated
  using (true);

create policy admin_all_contract_transfers
  on smartstay.contract_transfers
  to authenticated
  using ((select private.is_admin((select auth.uid()))))
  with check ((select private.is_admin((select auth.uid()))));

create policy authenticated_select_contract_addendums
  on smartstay.contract_addendums
  for select
  to authenticated
  using (true);

create policy admin_all_contract_addendums
  on smartstay.contract_addendums
  to authenticated
  using ((select private.is_admin((select auth.uid()))))
  with check ((select private.is_admin((select auth.uid()))));

create or replace function private.is_contract_participant(p_contract_id integer, p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from smartstay.contracts c
    join smartstay.tenants t on t.id = c.primary_tenant_id
    where c.id = p_contract_id
      and t.profile_id = p_user_id
      and coalesce(t.is_deleted, false) = false
      and coalesce(c.is_deleted, false) = false
  )
  or exists (
    select 1
    from smartstay.room_occupants ro
    join smartstay.tenants t on t.id = ro.tenant_id
    join smartstay.contracts c on c.id = ro.contract_id
    where ro.contract_id = p_contract_id
      and t.profile_id = p_user_id
      and coalesce(t.is_deleted, false) = false
      and coalesce(c.is_deleted, false) = false
  )
  or exists (
    select 1
    from smartstay.contract_tenants ct
    join smartstay.tenants t on t.id = ct.tenant_id
    join smartstay.contracts c on c.id = ct.contract_id
    where ct.contract_id = p_contract_id
      and t.profile_id = p_user_id
      and coalesce(t.is_deleted, false) = false
      and coalesce(c.is_deleted, false) = false
  );
$$;

create or replace function smartstay.create_contract_v2(
  p_room_id integer,
  p_start_date date,
  p_end_date date,
  p_monthly_rent numeric,
  p_deposit_amount numeric,
  p_payment_cycle_months integer,
  p_primary_tenant_id integer,
  p_occupant_ids integer[] default '{}'::integer[],
  p_payment_due_day integer default 5,
  p_service_ids integer[] default '{}'::integer[],
  p_service_prices numeric[] default '{}'::numeric[],
  p_service_quantities integer[] default '{}'::integer[],
  p_mark_deposit_received boolean default false
) returns jsonb
language plpgsql
set search_path = ''
as $$
declare
  v_contract_id integer;
  v_contract_code text;
  v_all_occupants integer[];
  v_occupant_count integer;
  v_idx integer;
begin
  if p_room_id is null or p_room_id <= 0 then
    raise exception 'Phòng không hợp lệ';
  end if;

  if p_primary_tenant_id is null or p_primary_tenant_id <= 0 then
    raise exception 'Tenant đại diện không hợp lệ';
  end if;

  if p_start_date is null or p_end_date is null or p_end_date <= p_start_date then
    raise exception 'Khoảng thời gian hợp đồng không hợp lệ';
  end if;

  if p_payment_due_day is null or p_payment_due_day < 1 or p_payment_due_day > 31 then
    raise exception 'Ngày đến hạn thanh toán phải nằm trong khoảng 1-31';
  end if;

  if not exists (
    select 1
    from smartstay.tenants t
    where t.id = p_primary_tenant_id
      and coalesce(t.is_deleted, false) = false
  ) then
    raise exception 'Không tìm thấy tenant đại diện';
  end if;

  v_all_occupants := array(
    select distinct item
    from unnest(array_append(coalesce(p_occupant_ids, '{}'::integer[]), p_primary_tenant_id)) as item
    where item is not null
  );

  v_occupant_count := coalesce(array_length(v_all_occupants, 1), 0);

  if v_occupant_count = 0 then
    raise exception 'Hợp đồng phải có ít nhất 1 người ở';
  end if;

  insert into smartstay.contracts (
    room_id,
    primary_tenant_id,
    start_date,
    end_date,
    signing_date,
    payment_cycle_months,
    payment_due_day,
    monthly_rent,
    deposit_amount,
    deposit_status,
    status,
    terms,
    is_deleted
  )
  values (
    p_room_id,
    p_primary_tenant_id,
    p_start_date,
    p_end_date,
    p_start_date,
    coalesce(p_payment_cycle_months, 1),
    p_payment_due_day,
    coalesce(p_monthly_rent, 0),
    coalesce(p_deposit_amount, 0),
    case when coalesce(p_mark_deposit_received, false) then 'received'::smartstay.deposit_status else 'pending'::smartstay.deposit_status end,
    'active'::smartstay.contract_status,
    jsonb_build_object(
      'occupants_for_billing', v_occupant_count,
      'contract_model', 'single_representative'
    ),
    false
  )
  returning id, contract_code into v_contract_id, v_contract_code;

  insert into smartstay.contract_tenants (contract_id, tenant_id, is_primary)
  values (v_contract_id, p_primary_tenant_id, true)
  on conflict (contract_id, tenant_id)
  do update set is_primary = excluded.is_primary;

  insert into smartstay.room_occupants (
    contract_id,
    room_id,
    tenant_id,
    is_primary_tenant,
    move_in_at,
    status
  )
  select
    v_contract_id,
    p_room_id,
    occupant_id,
    occupant_id = p_primary_tenant_id,
    p_start_date,
    'active'::smartstay.occupant_status
  from unnest(v_all_occupants) as occupant_id;

  if coalesce(array_length(p_service_ids, 1), 0) > 0 then
    for v_idx in 1..array_length(p_service_ids, 1) loop
      insert into smartstay.contract_services (
        contract_id,
        service_id,
        fixed_price,
        quantity
      )
      values (
        v_contract_id,
        p_service_ids[v_idx],
        coalesce(p_service_prices[v_idx], 0),
        coalesce(p_service_quantities[v_idx], 1)
      );
    end loop;
  end if;

  update smartstay.rooms
  set status = 'occupied'::smartstay.room_status,
      updated_at = now()
  where id = p_room_id
    and status <> 'occupied'::smartstay.room_status;

  return jsonb_build_object(
    'contractId', v_contract_id,
    'contractCode', v_contract_code
  );
end;
$$;

create or replace function smartstay.liquidate_contract(
  p_contract_id integer,
  p_termination_date date,
  p_reason text,
  p_deposit_used numeric default 0,
  p_additional_charges numeric default 0,
  p_processed_by uuid default auth.uid()
) returns jsonb
language plpgsql
set search_path = ''
as $$
declare
  v_room_id integer;
  v_deposit_amount numeric;
  v_remaining_active_contracts integer;
  v_unpaid_invoice_count integer;
begin
  select c.room_id, coalesce(c.deposit_amount, 0)
  into v_room_id, v_deposit_amount
  from smartstay.contracts c
  where c.id = p_contract_id
    and coalesce(c.is_deleted, false) = false
  for update;

  if v_room_id is null then
    raise exception 'Không tìm thấy hợp đồng để thanh lý';
  end if;

  select count(*)
  into v_unpaid_invoice_count
  from smartstay.invoices i
  where i.contract_id = p_contract_id
    and coalesce(i.status::text, 'draft') not in ('paid', 'cancelled')
    and coalesce(i.balance_due, 0) > 0;

  if v_unpaid_invoice_count > 0 then
    raise exception 'Cannot liquidate contract with unpaid invoices';
  end if;

  update smartstay.room_occupants
  set status = 'moved_out'::smartstay.occupant_status,
      move_out_at = coalesce(move_out_at, p_termination_date),
      updated_at = now()
  where contract_id = p_contract_id
    and status = 'active'::smartstay.occupant_status;

  update smartstay.contracts
  set status = 'terminated'::smartstay.contract_status,
      termination_reason = coalesce(nullif(p_reason, ''), 'Thanh lý hợp đồng'),
      terminated_at = coalesce(terminated_at, p_termination_date::timestamptz),
      updated_at = now(),
      terms = coalesce(terms, '{}'::jsonb) || jsonb_build_object('occupants_for_billing', 0)
  where id = p_contract_id;

  insert into smartstay.contract_terminations (
    contract_id,
    deposit_used,
    deposit_refunded,
    additional_charges,
    reason,
    processed_by
  )
  values (
    p_contract_id,
    greatest(coalesce(p_deposit_used, 0), 0),
    greatest(v_deposit_amount - greatest(coalesce(p_deposit_used, 0), 0) - greatest(coalesce(p_additional_charges, 0), 0), 0),
    greatest(coalesce(p_additional_charges, 0), 0),
    left(coalesce(nullif(p_reason, ''), 'Thanh lý hợp đồng'), 255),
    p_processed_by
  )
  on conflict (contract_id) do update
  set deposit_used = excluded.deposit_used,
      deposit_refunded = excluded.deposit_refunded,
      additional_charges = excluded.additional_charges,
      reason = excluded.reason,
      processed_by = excluded.processed_by;

  select count(*)
  into v_remaining_active_contracts
  from smartstay.contracts c
  where c.room_id = v_room_id
    and c.id <> p_contract_id
    and c.status in ('active', 'pending_signature')
    and coalesce(c.is_deleted, false) = false;

  if v_remaining_active_contracts = 0 then
    update smartstay.rooms
    set status = 'available'::smartstay.room_status,
        updated_at = now()
    where id = v_room_id;
  end if;

  return jsonb_build_object(
    'contractId', p_contract_id,
    'roomId', v_room_id,
    'status', 'terminated'
  );
end;
$$;

create or replace function smartstay.remove_contract_occupant(
  p_contract_id integer,
  p_tenant_id integer,
  p_move_out_date date,
  p_note text default null,
  p_processed_by uuid default auth.uid()
) returns jsonb
language plpgsql
set search_path = ''
as $$
declare
  v_is_primary boolean;
  v_remaining integer;
begin
  select ro.is_primary_tenant
  into v_is_primary
  from smartstay.room_occupants ro
  where ro.contract_id = p_contract_id
    and ro.tenant_id = p_tenant_id
    and ro.status = 'active'::smartstay.occupant_status
  for update;

  if v_is_primary is null then
    raise exception 'Không tìm thấy occupant còn hiệu lực trong hợp đồng';
  end if;

  if v_is_primary then
    raise exception 'Tenant đại diện rời đi phải dùng chuyển hợp đồng hoặc thanh lý';
  end if;

  update smartstay.room_occupants
  set status = 'moved_out'::smartstay.occupant_status,
      move_out_at = p_move_out_date,
      note = coalesce(p_note, note),
      updated_at = now()
  where contract_id = p_contract_id
    and tenant_id = p_tenant_id
    and status = 'active'::smartstay.occupant_status;

  select count(*)
  into v_remaining
  from smartstay.room_occupants ro
  where ro.contract_id = p_contract_id
    and ro.status = 'active'::smartstay.occupant_status;

  update smartstay.contracts c
  set terms = coalesce(c.terms, '{}'::jsonb) || jsonb_build_object('occupants_for_billing', v_remaining),
      updated_at = now()
  where c.id = p_contract_id;

  if v_remaining = 0 then
    perform smartstay.liquidate_contract(
      p_contract_id,
      p_move_out_date,
      'Tất cả người ở đã rời khỏi phòng',
      0,
      0,
      p_processed_by
    );
  end if;

  return jsonb_build_object(
    'contractId', p_contract_id,
    'tenantId', p_tenant_id,
    'remainingActiveOccupants', v_remaining,
    'autoLiquidated', v_remaining = 0
  );
end;
$$;

create or replace function smartstay.transfer_contract_representative(
  p_old_contract_id integer,
  p_to_tenant_id integer,
  p_transfer_date date,
  p_note text default null,
  p_approved_by uuid default auth.uid()
) returns jsonb
language plpgsql
set search_path = ''
as $$
declare
  v_old_contract smartstay.contracts%rowtype;
  v_old_primary_tenant_id integer;
  v_new_contract_id integer;
  v_new_contract_code text;
  v_remaining_occupants integer[];
  v_occupant_count integer;
begin
  select *
  into v_old_contract
  from smartstay.contracts
  where id = p_old_contract_id
    and coalesce(is_deleted, false) = false
  for update;

  if v_old_contract.id is null then
    raise exception 'Không tìm thấy hợp đồng cần chuyển';
  end if;

  if v_old_contract.status not in ('active', 'pending_signature') then
    raise exception 'Chỉ chuyển được hợp đồng đang hiệu lực';
  end if;

  v_old_primary_tenant_id := v_old_contract.primary_tenant_id;

  if v_old_primary_tenant_id is null then
    raise exception 'Hợp đồng hiện tại chưa có tenant đại diện';
  end if;

  if p_to_tenant_id = v_old_primary_tenant_id then
    raise exception 'Tenant nhận chuyển phải khác tenant đại diện hiện tại';
  end if;

  if not exists (
    select 1
    from smartstay.room_occupants ro
    where ro.contract_id = p_old_contract_id
      and ro.tenant_id = p_to_tenant_id
      and ro.status = 'active'::smartstay.occupant_status
  ) then
    raise exception 'Tenant nhận chuyển phải là occupant còn ở lại';
  end if;

  v_remaining_occupants := array(
    select ro.tenant_id
    from smartstay.room_occupants ro
    where ro.contract_id = p_old_contract_id
      and ro.status = 'active'::smartstay.occupant_status
      and ro.tenant_id <> v_old_primary_tenant_id
    order by ro.is_primary_tenant desc, ro.id asc
  );

  v_occupant_count := coalesce(array_length(v_remaining_occupants, 1), 0);

  if v_occupant_count = 0 then
    raise exception 'Không còn occupant ở lại để nhận chuyển hợp đồng';
  end if;

  update smartstay.contracts
  set status = 'terminated'::smartstay.contract_status,
      termination_reason = 'Chuyển hợp đồng sang tenant mới',
      terminated_at = coalesce(terminated_at, p_transfer_date::timestamptz),
      updated_at = now()
  where id = p_old_contract_id;

  update smartstay.room_occupants
  set status = 'moved_out'::smartstay.occupant_status,
      move_out_at = coalesce(move_out_at, p_transfer_date),
      updated_at = now()
  where contract_id = p_old_contract_id
    and status = 'active'::smartstay.occupant_status;

  insert into smartstay.contracts (
    room_id,
    primary_tenant_id,
    linked_contract_id,
    start_date,
    end_date,
    signing_date,
    payment_cycle_months,
    payment_due_day,
    monthly_rent,
    deposit_amount,
    deposit_status,
    status,
    terms,
    is_deleted
  )
  values (
    v_old_contract.room_id,
    p_to_tenant_id,
    p_old_contract_id,
    p_transfer_date,
    v_old_contract.end_date,
    p_transfer_date,
    v_old_contract.payment_cycle_months,
    coalesce(v_old_contract.payment_due_day, 5),
    v_old_contract.monthly_rent,
    v_old_contract.deposit_amount,
    v_old_contract.deposit_status,
    'active'::smartstay.contract_status,
    coalesce(v_old_contract.terms, '{}'::jsonb)
      || jsonb_build_object(
        'occupants_for_billing', v_occupant_count,
        'transferred_from_contract_id', p_old_contract_id
      ),
    false
  )
  returning id, contract_code into v_new_contract_id, v_new_contract_code;

  update smartstay.contracts
  set linked_contract_id = v_new_contract_id
  where id = p_old_contract_id;

  insert into smartstay.contract_tenants (contract_id, tenant_id, is_primary)
  values (v_new_contract_id, p_to_tenant_id, true)
  on conflict (contract_id, tenant_id)
  do update set is_primary = true;

  insert into smartstay.room_occupants (
    contract_id,
    room_id,
    tenant_id,
    is_primary_tenant,
    move_in_at,
    status
  )
  select
    v_new_contract_id,
    v_old_contract.room_id,
    occupant_id,
    occupant_id = p_to_tenant_id,
    p_transfer_date,
    'active'::smartstay.occupant_status
  from unnest(v_remaining_occupants) as occupant_id;

  insert into smartstay.contract_terminations (
    contract_id,
    deposit_used,
    deposit_refunded,
    additional_charges,
    reason,
    processed_by
  )
  values (
    p_old_contract_id,
    0,
    0,
    0,
    'Chuyển hợp đồng sang tenant mới',
    p_approved_by
  )
  on conflict (contract_id) do update
  set reason = excluded.reason,
      processed_by = excluded.processed_by;

  insert into smartstay.contract_transfers (
    old_contract_id,
    new_contract_id,
    room_id,
    from_tenant_id,
    to_tenant_id,
    transfer_date,
    approved_by,
    status,
    deposit_mode,
    carry_over_deposit_amount,
    note
  )
  values (
    p_old_contract_id,
    v_new_contract_id,
    v_old_contract.room_id,
    v_old_primary_tenant_id,
    p_to_tenant_id,
    p_transfer_date,
    p_approved_by,
    'completed'::smartstay.contract_transfer_status,
    'carry_over',
    coalesce(v_old_contract.deposit_amount, 0),
    p_note
  );

  update smartstay.rooms
  set status = 'occupied'::smartstay.room_status,
      updated_at = now()
  where id = v_old_contract.room_id;

  return jsonb_build_object(
    'oldContractId', p_old_contract_id,
    'newContractId', v_new_contract_id,
    'newContractCode', v_new_contract_code
  );
end;
$$;
