set check_function_bodies = off;
set search_path = smartstay, public;

alter table smartstay.profiles
  add column if not exists tenant_stage text;

update smartstay.profiles as p
set tenant_stage = case
  when exists (
    select 1
    from smartstay.tenants t
    join smartstay.contract_tenants ct on ct.tenant_id = t.id
    join smartstay.contracts c on c.id = ct.contract_id
    where t.profile_id = p.id
      and coalesce(t.is_deleted, false) = false
      and coalesce(c.is_deleted, false) = false
      and c.status = 'active'
  ) then 'resident_active'
  when exists (
    select 1
    from smartstay.tenants t
    where t.profile_id = p.id
      and coalesce(t.is_deleted, false) = false
  ) then 'resident_pending_onboarding'
  else coalesce(p.tenant_stage, 'prospect')
end
where p.tenant_stage is null
   or p.tenant_stage not in ('prospect', 'applicant', 'resident_pending_onboarding', 'resident_active');

update smartstay.profiles
set tenant_stage = 'prospect'
where tenant_stage is null;

alter table smartstay.profiles
  alter column tenant_stage set default 'prospect';

alter table smartstay.profiles
  alter column tenant_stage set not null;

alter table smartstay.profiles
  drop constraint if exists profiles_tenant_stage_check;

alter table smartstay.profiles
  add constraint profiles_tenant_stage_check
  check (tenant_stage in ('prospect', 'applicant', 'resident_pending_onboarding', 'resident_active'));

create table if not exists smartstay.rental_applications (
  id bigint generated by default as identity primary key,
  uuid uuid not null default gen_random_uuid() unique,
  profile_id uuid not null references smartstay.profiles(id) on delete cascade,
  room_id bigint not null references smartstay.rooms(id) on delete cascade,
  status text not null default 'draft',
  verification_method text,
  verification_payload jsonb not null default '{}'::jsonb,
  notes text,
  submitted_at timestamptz,
  reviewed_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint rental_applications_status_check
    check (status in ('draft', 'submitted', 'under_review', 'approved', 'rejected', 'cancelled'))
);

create index if not exists rental_applications_profile_id_idx
  on smartstay.rental_applications(profile_id);

create index if not exists rental_applications_room_id_idx
  on smartstay.rental_applications(room_id);

create index if not exists rental_applications_status_idx
  on smartstay.rental_applications(status);

create unique index if not exists rental_applications_open_profile_room_idx
  on smartstay.rental_applications(profile_id, room_id)
  where status in ('draft', 'submitted', 'under_review');

drop trigger if exists set_rental_applications_updated_at on smartstay.rental_applications;

create trigger set_rental_applications_updated_at
before update on smartstay.rental_applications
for each row
execute function smartstay.trigger_set_updated_at();

alter table smartstay.rental_applications enable row level security;

drop policy if exists rental_applications_applicant_self on smartstay.rental_applications;
create policy rental_applications_applicant_self
on smartstay.rental_applications
for all
to authenticated
using (profile_id = auth.uid())
with check (profile_id = auth.uid());

drop policy if exists rental_applications_management_all on smartstay.rental_applications;
create policy rental_applications_management_all
on smartstay.rental_applications
for all
to authenticated
using (
  exists (
    select 1
    from smartstay.profiles p
    where p.id = auth.uid()
      and p.role in ('admin', 'manager', 'staff', 'landlord')
  )
)
with check (
  exists (
    select 1
    from smartstay.profiles p
    where p.id = auth.uid()
      and p.role in ('admin', 'manager', 'staff', 'landlord')
  )
);

create or replace view smartstay.public_room_listings as
select
  r.id as room_id,
  r.uuid as room_uuid,
  r.room_code,
  r.room_type,
  r.area_sqm,
  r.base_rent,
  r.max_occupants,
  r.floor_number,
  r.has_balcony,
  r.has_private_bathroom,
  r.facing,
  r.condition_score,
  r.amenities as room_amenities,
  b.id as building_id,
  b.uuid as building_uuid,
  b.name as building_name,
  b.address as building_address,
  b.description as building_description,
  b.amenities as building_amenities,
  'available_now'::text as availability_status
from smartstay.rooms r
join smartstay.buildings b on b.id = r.building_id
where coalesce(r.is_deleted, false) = false
  and coalesce(b.is_deleted, false) = false
  and r.status = 'available';

grant select on smartstay.public_room_listings to anon, authenticated;
grant select, insert, update on smartstay.rental_applications to authenticated;
grant usage, select on sequence smartstay.rental_applications_id_seq to authenticated;
