set search_path = smartstay, public;

create table if not exists smartstay.amenity_policies (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  service_id bigint not null references smartstay.services(id) on delete cascade,
  building_id bigint null references smartstay.buildings(id) on delete set null,
  booking_mode text not null default 'slot_based'
    check (booking_mode in ('slot_based', 'capacity_based', 'open_access')),
  charge_mode text not null default 'free'
    check (charge_mode in ('free', 'fixed_per_booking', 'fixed_per_person')),
  status text not null default 'draft'
    check (status in ('draft', 'pending_approval', 'approved', 'archived')),
  slot_granularity_minutes integer not null default 60 check (slot_granularity_minutes > 0),
  max_capacity_per_slot integer not null default 1 check (max_capacity_per_slot > 0),
  max_advance_days integer not null default 7 check (max_advance_days >= 0),
  cancellation_cutoff_hours integer not null default 2 check (cancellation_cutoff_hours >= 0),
  auto_complete_after_minutes integer not null default 90 check (auto_complete_after_minutes >= 0),
  allow_waitlist boolean not null default false,
  requires_staff_approval boolean not null default false,
  requires_checkin boolean not null default true,
  price_override_amount numeric(12,2) null check (price_override_amount is null or price_override_amount >= 0),
  active_from date not null default current_date,
  active_to date null,
  rules_json jsonb not null default '{}'::jsonb,
  current_version_no integer not null default 1 check (current_version_no > 0),
  notes text null,
  created_by uuid null references smartstay.profiles(id) on delete set null,
  approved_by uuid null references smartstay.profiles(id) on delete set null,
  approved_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null,
  constraint amenity_policies_active_range_ck check (active_to is null or active_to >= active_from)
);

create index if not exists amenity_policies_service_idx
  on smartstay.amenity_policies(service_id, status, active_from desc);

create index if not exists amenity_policies_building_idx
  on smartstay.amenity_policies(building_id, status, active_from desc);

create table if not exists smartstay.amenity_policy_versions (
  id bigint generated by default as identity primary key,
  policy_id bigint not null references smartstay.amenity_policies(id) on delete cascade,
  version_no integer not null check (version_no > 0),
  change_type text not null default 'draft'
    check (change_type in ('draft', 'create', 'update', 'approval', 'archive')),
  status text not null default 'draft'
    check (status in ('draft', 'pending_approval', 'approved', 'rejected', 'archived')),
  change_summary text null,
  snapshot_json jsonb not null default '{}'::jsonb,
  submitted_by uuid null references smartstay.profiles(id) on delete set null,
  submitted_at timestamptz not null default now(),
  reviewed_by uuid null references smartstay.profiles(id) on delete set null,
  reviewed_at timestamptz null,
  review_note text null,
  created_at timestamptz not null default now(),
  constraint amenity_policy_versions_policy_version_uniq unique (policy_id, version_no)
);

create index if not exists amenity_policy_versions_status_idx
  on smartstay.amenity_policy_versions(status, submitted_at desc);

create table if not exists smartstay.amenity_policy_notifications (
  id bigint generated by default as identity primary key,
  policy_id bigint not null references smartstay.amenity_policies(id) on delete cascade,
  version_id bigint null references smartstay.amenity_policy_versions(id) on delete set null,
  audience_scope text not null default 'active_residents'
    check (audience_scope in ('active_residents', 'building_residents', 'manual_selection')),
  channel text not null default 'in_app'
    check (channel in ('in_app', 'email', 'sms')),
  title text not null,
  message text not null,
  payload_json jsonb not null default '{}'::jsonb,
  status text not null default 'queued'
    check (status in ('queued', 'sent', 'failed', 'cancelled')),
  created_by uuid null references smartstay.profiles(id) on delete set null,
  sent_at timestamptz null,
  created_at timestamptz not null default now()
);

create index if not exists amenity_policy_notifications_status_idx
  on smartstay.amenity_policy_notifications(status, created_at desc);

create table if not exists smartstay.amenity_booking_exceptions (
  id bigint generated by default as identity primary key,
  policy_id bigint null references smartstay.amenity_policies(id) on delete set null,
  service_id bigint not null references smartstay.services(id) on delete cascade,
  building_id bigint null references smartstay.buildings(id) on delete set null,
  room_id bigint null references smartstay.rooms(id) on delete set null,
  title text not null,
  exception_type text not null
    check (exception_type in ('closure', 'blackout', 'capacity_override', 'price_override', 'rule_override')),
  start_at timestamptz not null,
  end_at timestamptz not null,
  override_json jsonb not null default '{}'::jsonb,
  reason text null,
  is_active boolean not null default true,
  created_by uuid null references smartstay.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint amenity_booking_exceptions_window_ck check (end_at > start_at)
);

create index if not exists amenity_booking_exceptions_active_idx
  on smartstay.amenity_booking_exceptions(service_id, is_active, start_at desc);

create table if not exists smartstay.amenity_bookings (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references smartstay.tenants(id) on delete cascade,
  service_id bigint not null references smartstay.services(id) on delete cascade,
  building_id bigint null references smartstay.buildings(id) on delete set null,
  room_id bigint null references smartstay.rooms(id) on delete set null,
  policy_id bigint null references smartstay.amenity_policies(id) on delete set null,
  booking_date date not null,
  slot_start_at timestamptz null,
  slot_end_at timestamptz null,
  time_slot text not null,
  party_size integer not null default 1 check (party_size > 0),
  amount numeric(12,2) not null default 0,
  status text not null default 'booked'
    check (status in ('booked', 'pending_approval', 'approved', 'in_use', 'completed', 'cancelled', 'no_show')),
  note text null,
  created_by uuid null references smartstay.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists amenity_bookings_tenant_date_idx
  on smartstay.amenity_bookings(tenant_id, booking_date desc, created_at desc);

create index if not exists amenity_bookings_service_slot_idx
  on smartstay.amenity_bookings(service_id, booking_date, time_slot, status);

create table if not exists smartstay.amenity_booking_checkins (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references smartstay.amenity_bookings(id) on delete cascade,
  status text not null default 'checked_in'
    check (status in ('checked_in', 'checked_out', 'no_show')),
  checked_in_at timestamptz null,
  checked_out_at timestamptz null,
  checked_in_by uuid null references smartstay.profiles(id) on delete set null,
  checked_out_by uuid null references smartstay.profiles(id) on delete set null,
  note text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists amenity_booking_checkins_booking_idx
  on smartstay.amenity_booking_checkins(booking_id, created_at desc);

drop trigger if exists trg_amenity_policies_updated_at on smartstay.amenity_policies;
create trigger trg_amenity_policies_updated_at
before update on smartstay.amenity_policies
for each row execute function smartstay.trigger_set_updated_at();

drop trigger if exists trg_amenity_booking_exceptions_updated_at on smartstay.amenity_booking_exceptions;
create trigger trg_amenity_booking_exceptions_updated_at
before update on smartstay.amenity_booking_exceptions
for each row execute function smartstay.trigger_set_updated_at();

drop trigger if exists trg_amenity_bookings_updated_at on smartstay.amenity_bookings;
create trigger trg_amenity_bookings_updated_at
before update on smartstay.amenity_bookings
for each row execute function smartstay.trigger_set_updated_at();

drop trigger if exists trg_amenity_booking_checkins_updated_at on smartstay.amenity_booking_checkins;
create trigger trg_amenity_booking_checkins_updated_at
before update on smartstay.amenity_booking_checkins
for each row execute function smartstay.trigger_set_updated_at();

alter table smartstay.amenity_policies enable row level security;
alter table smartstay.amenity_policies force row level security;
alter table smartstay.amenity_policy_versions enable row level security;
alter table smartstay.amenity_policy_versions force row level security;
alter table smartstay.amenity_policy_notifications enable row level security;
alter table smartstay.amenity_policy_notifications force row level security;
alter table smartstay.amenity_booking_exceptions enable row level security;
alter table smartstay.amenity_booking_exceptions force row level security;
alter table smartstay.amenity_bookings enable row level security;
alter table smartstay.amenity_bookings force row level security;
alter table smartstay.amenity_booking_checkins enable row level security;
alter table smartstay.amenity_booking_checkins force row level security;

drop policy if exists amenity_policies_admin_all on smartstay.amenity_policies;
create policy amenity_policies_admin_all
on smartstay.amenity_policies
for all to authenticated
using ((select private.is_admin((select auth.uid()))))
with check ((select private.is_admin((select auth.uid()))));

drop policy if exists amenity_policy_versions_admin_all on smartstay.amenity_policy_versions;
create policy amenity_policy_versions_admin_all
on smartstay.amenity_policy_versions
for all to authenticated
using ((select private.is_admin((select auth.uid()))))
with check ((select private.is_admin((select auth.uid()))));

drop policy if exists amenity_policy_notifications_admin_all on smartstay.amenity_policy_notifications;
create policy amenity_policy_notifications_admin_all
on smartstay.amenity_policy_notifications
for all to authenticated
using ((select private.is_admin((select auth.uid()))))
with check ((select private.is_admin((select auth.uid()))));

drop policy if exists amenity_booking_exceptions_admin_all on smartstay.amenity_booking_exceptions;
create policy amenity_booking_exceptions_admin_all
on smartstay.amenity_booking_exceptions
for all to authenticated
using ((select private.is_admin((select auth.uid()))))
with check ((select private.is_admin((select auth.uid()))));

drop policy if exists amenity_bookings_admin_all on smartstay.amenity_bookings;
create policy amenity_bookings_admin_all
on smartstay.amenity_bookings
for all to authenticated
using ((select private.is_admin((select auth.uid()))))
with check ((select private.is_admin((select auth.uid()))));

drop policy if exists amenity_bookings_tenant_select_own on smartstay.amenity_bookings;
create policy amenity_bookings_tenant_select_own
on smartstay.amenity_bookings
for select to authenticated
using (
  exists (
    select 1
    from smartstay.tenants t
    where t.id = amenity_bookings.tenant_id
      and t.profile_id = auth.uid()
      and coalesce(t.is_deleted, false) = false
  )
);

drop policy if exists amenity_bookings_tenant_insert_own on smartstay.amenity_bookings;
create policy amenity_bookings_tenant_insert_own
on smartstay.amenity_bookings
for insert to authenticated
with check (
  exists (
    select 1
    from smartstay.tenants t
    where t.id = amenity_bookings.tenant_id
      and t.profile_id = auth.uid()
      and coalesce(t.is_deleted, false) = false
  )
);

drop policy if exists amenity_bookings_tenant_update_own on smartstay.amenity_bookings;
create policy amenity_bookings_tenant_update_own
on smartstay.amenity_bookings
for update to authenticated
using (
  exists (
    select 1
    from smartstay.tenants t
    where t.id = amenity_bookings.tenant_id
      and t.profile_id = auth.uid()
      and coalesce(t.is_deleted, false) = false
  )
)
with check (
  exists (
    select 1
    from smartstay.tenants t
    where t.id = amenity_bookings.tenant_id
      and t.profile_id = auth.uid()
      and coalesce(t.is_deleted, false) = false
  )
);

drop policy if exists amenity_booking_checkins_admin_all on smartstay.amenity_booking_checkins;
create policy amenity_booking_checkins_admin_all
on smartstay.amenity_booking_checkins
for all to authenticated
using ((select private.is_admin((select auth.uid()))))
with check ((select private.is_admin((select auth.uid()))));

insert into smartstay.system_settings (key, value, group_name, description, is_sensitive)
values
  ('utility.meter_reading_day', '5'::jsonb, 'billing', 'Ngay chot cong to cho luong legacy metered.', false),
  ('billing.invoice_issue_day', '1'::jsonb, 'billing', 'Ngay xuat hoa don hang thang.', false),
  ('billing.max_overdue_days', '15'::jsonb, 'billing', 'So ngay no toi da truoc khi canh bao xu ly no.', false),
  ('contract.deposit_per_person', '1000000'::jsonb, 'contract', 'Muc coc mac dinh theo dau nguoi.', false)
on conflict (key) do nothing;
