set search_path = smartstay, public;

create table if not exists smartstay.amenity_catalog (
  id bigint generated by default as identity primary key,
  legacy_service_id integer unique null references smartstay.services(id) on delete set null,
  code text not null unique,
  name text not null,
  description text null,
  building_id bigint null references smartstay.buildings(id) on delete set null,
  is_active boolean not null default true,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists smartstay.service_catalog (
  id bigint generated by default as identity primary key,
  legacy_service_id integer unique null references smartstay.services(id) on delete set null,
  code text not null unique,
  name text not null,
  description text null,
  service_kind text not null default 'fixed_recurring'
    check (service_kind in ('fixed_recurring')),
  billing_method text not null default 'fixed'
    check (billing_method in ('fixed', 'per_person', 'per_room', 'per_unit')),
  unit text not null default 'thang',
  is_active boolean not null default true,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists smartstay.amenity_booking_charges (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references smartstay.amenity_bookings(id) on delete cascade,
  invoice_id integer null references smartstay.invoices(id) on delete set null,
  billing_period text null,
  amount numeric(12,2) not null default 0 check (amount >= 0),
  status text not null default 'pending'
    check (status in ('pending', 'invoiced', 'waived', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists amenity_catalog_active_idx
  on smartstay.amenity_catalog(is_active, is_deleted, name);

create index if not exists service_catalog_active_idx
  on smartstay.service_catalog(service_kind, is_active, is_deleted, name);

create index if not exists amenity_booking_charges_pending_idx
  on smartstay.amenity_booking_charges(status, billing_period, booking_id);

with amenity_source as (
  select distinct s.id, s.name, s.is_active, s.is_deleted, s.created_at, s.updated_at
  from smartstay.services s
  where exists (select 1 from smartstay.amenity_policies ap where ap.service_id = s.id)
     or exists (select 1 from smartstay.amenity_bookings ab where ab.service_id = s.id)
     or exists (select 1 from smartstay.amenity_booking_exceptions abe where abe.service_id = s.id)
)
insert into smartstay.amenity_catalog (
  id,
  legacy_service_id,
  code,
  name,
  is_active,
  is_deleted,
  created_at,
  updated_at
)
select
  src.id::bigint,
  src.id,
  concat('AMN-', lpad(src.id::text, 4, '0')),
  src.name,
  coalesce(src.is_active, true),
  coalesce(src.is_deleted, false),
  coalesce(src.created_at, now()),
  coalesce(src.updated_at, now())
from amenity_source src
on conflict (id) do update
set
  legacy_service_id = excluded.legacy_service_id,
  name = excluded.name,
  is_active = excluded.is_active,
  is_deleted = excluded.is_deleted,
  updated_at = now();

with service_source as (
  select s.id, s.name, s.calc_type, s.is_active, s.is_deleted, s.created_at, s.updated_at
  from smartstay.services s
  where lower(s.name) not in ('electricity', 'water', 'electric', 'dien', 'nuoc')
)
insert into smartstay.service_catalog (
  id,
  legacy_service_id,
  code,
  name,
  service_kind,
  billing_method,
  unit,
  is_active,
  is_deleted,
  created_at,
  updated_at
)
select
  src.id::bigint,
  src.id,
  concat('SRV-', lpad(src.id::text, 4, '0')),
  src.name,
  'fixed_recurring',
  case src.calc_type
    when 'per_person' then 'per_person'
    when 'per_room' then 'per_room'
    when 'per_unit' then 'per_unit'
    else 'fixed'
  end,
  case src.calc_type
    when 'per_person' then 'nguoi/thang'
    when 'per_room' then 'phong/thang'
    when 'per_unit' then 'so_luong'
    else 'thang'
  end,
  coalesce(src.is_active, true),
  coalesce(src.is_deleted, false),
  coalesce(src.created_at, now()),
  coalesce(src.updated_at, now())
from service_source src
on conflict (id) do update
set
  legacy_service_id = excluded.legacy_service_id,
  name = excluded.name,
  billing_method = excluded.billing_method,
  unit = excluded.unit,
  is_active = excluded.is_active,
  is_deleted = excluded.is_deleted,
  updated_at = now();

select setval(
  pg_get_serial_sequence('smartstay.amenity_catalog', 'id'),
  greatest(coalesce((select max(id) from smartstay.amenity_catalog), 1), 1),
  true
);

select setval(
  pg_get_serial_sequence('smartstay.service_catalog', 'id'),
  greatest(coalesce((select max(id) from smartstay.service_catalog), 1), 1),
  true
);

alter table smartstay.amenity_policies
  add column if not exists amenity_id bigint;

alter table smartstay.amenity_booking_exceptions
  add column if not exists amenity_id bigint;

alter table smartstay.amenity_bookings
  add column if not exists amenity_id bigint;

alter table smartstay.service_prices
  add column if not exists service_catalog_id bigint;

alter table smartstay.contract_services
  add column if not exists service_catalog_id bigint;

alter table smartstay.amenity_policies
  alter column service_id drop not null;

alter table smartstay.amenity_booking_exceptions
  alter column service_id drop not null;

alter table smartstay.amenity_bookings
  alter column service_id drop not null;

alter table smartstay.service_prices
  alter column service_id drop not null;

alter table smartstay.contract_services
  alter column service_id drop not null;

update smartstay.amenity_policies ap
set amenity_id = ac.id
from smartstay.amenity_catalog ac
where ac.legacy_service_id = ap.service_id
  and ap.amenity_id is null;

update smartstay.amenity_booking_exceptions abe
set amenity_id = ac.id
from smartstay.amenity_catalog ac
where ac.legacy_service_id = abe.service_id
  and abe.amenity_id is null;

update smartstay.amenity_bookings ab
set amenity_id = ac.id
from smartstay.amenity_catalog ac
where ac.legacy_service_id = ab.service_id
  and ab.amenity_id is null;

update smartstay.service_prices sp
set service_catalog_id = sc.id
from smartstay.service_catalog sc
where sc.legacy_service_id = sp.service_id
  and sp.service_catalog_id is null;

update smartstay.contract_services cs
set service_catalog_id = sc.id
from smartstay.service_catalog sc
where sc.legacy_service_id = cs.service_id
  and cs.service_catalog_id is null;

create or replace function smartstay.sync_amenity_legacy_refs()
returns trigger
language plpgsql
set search_path = smartstay, public
as $$
begin
  if new.amenity_id is null and new.service_id is not null then
    select ac.id
      into new.amenity_id
    from smartstay.amenity_catalog ac
    where ac.legacy_service_id = new.service_id
    limit 1;
  end if;

  if new.service_id is null and new.amenity_id is not null then
    select ac.legacy_service_id
      into new.service_id
    from smartstay.amenity_catalog ac
    where ac.id = new.amenity_id
    limit 1;
  end if;

  return new;
end;
$$;

create or replace function smartstay.sync_service_catalog_legacy_refs()
returns trigger
language plpgsql
set search_path = smartstay, public
as $$
begin
  if new.service_catalog_id is null and new.service_id is not null then
    select sc.id
      into new.service_catalog_id
    from smartstay.service_catalog sc
    where sc.legacy_service_id = new.service_id
    limit 1;
  end if;

  if new.service_id is null and new.service_catalog_id is not null then
    select sc.legacy_service_id
      into new.service_id
    from smartstay.service_catalog sc
    where sc.id = new.service_catalog_id
    limit 1;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_amenity_policies_sync_refs on smartstay.amenity_policies;
create trigger trg_amenity_policies_sync_refs
before insert or update on smartstay.amenity_policies
for each row execute function smartstay.sync_amenity_legacy_refs();

drop trigger if exists trg_amenity_booking_exceptions_sync_refs on smartstay.amenity_booking_exceptions;
create trigger trg_amenity_booking_exceptions_sync_refs
before insert or update on smartstay.amenity_booking_exceptions
for each row execute function smartstay.sync_amenity_legacy_refs();

drop trigger if exists trg_amenity_bookings_sync_refs on smartstay.amenity_bookings;
create trigger trg_amenity_bookings_sync_refs
before insert or update on smartstay.amenity_bookings
for each row execute function smartstay.sync_amenity_legacy_refs();

drop trigger if exists trg_service_prices_sync_refs on smartstay.service_prices;
create trigger trg_service_prices_sync_refs
before insert or update on smartstay.service_prices
for each row execute function smartstay.sync_service_catalog_legacy_refs();

drop trigger if exists trg_contract_services_sync_refs on smartstay.contract_services;
create trigger trg_contract_services_sync_refs
before insert or update on smartstay.contract_services
for each row execute function smartstay.sync_service_catalog_legacy_refs();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'amenity_policies_amenity_id_fkey'
      and conrelid = 'smartstay.amenity_policies'::regclass
  ) then
    alter table smartstay.amenity_policies
      add constraint amenity_policies_amenity_id_fkey
      foreign key (amenity_id) references smartstay.amenity_catalog(id) on delete cascade;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'amenity_booking_exceptions_amenity_id_fkey'
      and conrelid = 'smartstay.amenity_booking_exceptions'::regclass
  ) then
    alter table smartstay.amenity_booking_exceptions
      add constraint amenity_booking_exceptions_amenity_id_fkey
      foreign key (amenity_id) references smartstay.amenity_catalog(id) on delete cascade;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'amenity_bookings_amenity_id_fkey'
      and conrelid = 'smartstay.amenity_bookings'::regclass
  ) then
    alter table smartstay.amenity_bookings
      add constraint amenity_bookings_amenity_id_fkey
      foreign key (amenity_id) references smartstay.amenity_catalog(id) on delete cascade;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'service_prices_service_catalog_id_fkey'
      and conrelid = 'smartstay.service_prices'::regclass
  ) then
    alter table smartstay.service_prices
      add constraint service_prices_service_catalog_id_fkey
      foreign key (service_catalog_id) references smartstay.service_catalog(id) on delete cascade;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'contract_services_service_catalog_id_fkey'
      and conrelid = 'smartstay.contract_services'::regclass
  ) then
    alter table smartstay.contract_services
      add constraint contract_services_service_catalog_id_fkey
      foreign key (service_catalog_id) references smartstay.service_catalog(id) on delete restrict;
  end if;
end
$$;

create index if not exists amenity_policies_amenity_idx
  on smartstay.amenity_policies(amenity_id, status, active_from desc);

create index if not exists amenity_booking_exceptions_amenity_active_idx
  on smartstay.amenity_booking_exceptions(amenity_id, is_active, start_at desc);

create index if not exists amenity_bookings_amenity_slot_idx
  on smartstay.amenity_bookings(amenity_id, booking_date, time_slot, status);

create index if not exists contract_services_contract_service_catalog_idx
  on smartstay.contract_services(contract_id, service_catalog_id);

create index if not exists service_prices_service_catalog_active_idx
  on smartstay.service_prices(service_catalog_id, is_active, effective_from desc);

create unique index if not exists contract_services_unique_fixed_service
  on smartstay.contract_services(contract_id, service_catalog_id)
  where service_catalog_id is not null;

grant usage on schema smartstay to anon, authenticated, service_role;
grant select, insert, update, delete on table smartstay.amenity_catalog to authenticated, service_role;
grant select, insert, update, delete on table smartstay.service_catalog to authenticated, service_role;
grant select, insert, update, delete on table smartstay.amenity_booking_charges to authenticated, service_role;
grant usage, select on sequence smartstay.amenity_catalog_id_seq to authenticated, service_role;
grant usage, select on sequence smartstay.service_catalog_id_seq to authenticated, service_role;
grant usage, select on sequence smartstay.amenity_booking_charges_id_seq to authenticated, service_role;

alter table smartstay.amenity_catalog enable row level security;
alter table smartstay.service_catalog enable row level security;
alter table smartstay.amenity_booking_charges enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'smartstay' and tablename = 'amenity_catalog' and policyname = 'admin_all_amenity_catalog'
  ) then
    create policy admin_all_amenity_catalog
      on smartstay.amenity_catalog
      for all
      to authenticated
      using (
        exists (
          select 1
          from smartstay.profiles
          where profiles.id = auth.uid()
            and profiles.role = any (array['admin'::smartstay.user_role, 'manager'::smartstay.user_role, 'staff'::smartstay.user_role, 'landlord'::smartstay.user_role])
        )
      )
      with check (
        exists (
          select 1
          from smartstay.profiles
          where profiles.id = auth.uid()
            and profiles.role = any (array['admin'::smartstay.user_role, 'manager'::smartstay.user_role, 'staff'::smartstay.user_role, 'landlord'::smartstay.user_role])
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'smartstay' and tablename = 'amenity_catalog' and policyname = 'authenticated_select_amenity_catalog'
  ) then
    create policy authenticated_select_amenity_catalog
      on smartstay.amenity_catalog
      for select
      to authenticated
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'smartstay' and tablename = 'service_catalog' and policyname = 'admin_all_service_catalog'
  ) then
    create policy admin_all_service_catalog
      on smartstay.service_catalog
      for all
      to authenticated
      using (
        exists (
          select 1
          from smartstay.profiles
          where profiles.id = auth.uid()
            and profiles.role = any (array['admin'::smartstay.user_role, 'manager'::smartstay.user_role, 'staff'::smartstay.user_role, 'landlord'::smartstay.user_role])
        )
      )
      with check (
        exists (
          select 1
          from smartstay.profiles
          where profiles.id = auth.uid()
            and profiles.role = any (array['admin'::smartstay.user_role, 'manager'::smartstay.user_role, 'staff'::smartstay.user_role, 'landlord'::smartstay.user_role])
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'smartstay' and tablename = 'service_catalog' and policyname = 'authenticated_select_service_catalog'
  ) then
    create policy authenticated_select_service_catalog
      on smartstay.service_catalog
      for select
      to authenticated
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'smartstay' and tablename = 'amenity_booking_charges' and policyname = 'admin_all_amenity_booking_charges'
  ) then
    create policy admin_all_amenity_booking_charges
      on smartstay.amenity_booking_charges
      for all
      to authenticated
      using (
        exists (
          select 1
          from smartstay.profiles
          where profiles.id = auth.uid()
            and profiles.role = any (array['admin'::smartstay.user_role, 'manager'::smartstay.user_role, 'staff'::smartstay.user_role, 'landlord'::smartstay.user_role])
        )
      )
      with check (
        exists (
          select 1
          from smartstay.profiles
          where profiles.id = auth.uid()
            and profiles.role = any (array['admin'::smartstay.user_role, 'manager'::smartstay.user_role, 'staff'::smartstay.user_role, 'landlord'::smartstay.user_role])
        )
      );
  end if;
end
$$;

create or replace function smartstay.get_domain_schema_health()
returns jsonb
language sql
stable
set search_path = smartstay, public
as $$
  select jsonb_build_object(
    'amenity_catalog_exists', to_regclass('smartstay.amenity_catalog') is not null,
    'service_catalog_exists', to_regclass('smartstay.service_catalog') is not null,
    'amenity_policies_has_amenity_id', exists (
      select 1 from information_schema.columns
      where table_schema = 'smartstay' and table_name = 'amenity_policies' and column_name = 'amenity_id'
    ),
    'amenity_bookings_has_amenity_id', exists (
      select 1 from information_schema.columns
      where table_schema = 'smartstay' and table_name = 'amenity_bookings' and column_name = 'amenity_id'
    ),
    'amenity_booking_exceptions_has_amenity_id', exists (
      select 1 from information_schema.columns
      where table_schema = 'smartstay' and table_name = 'amenity_booking_exceptions' and column_name = 'amenity_id'
    ),
    'service_prices_has_service_catalog_id', exists (
      select 1 from information_schema.columns
      where table_schema = 'smartstay' and table_name = 'service_prices' and column_name = 'service_catalog_id'
    ),
    'contract_services_has_service_catalog_id', exists (
      select 1 from information_schema.columns
      where table_schema = 'smartstay' and table_name = 'contract_services' and column_name = 'service_catalog_id'
    ),
    'amenity_catalog_count', coalesce((select count(*) from smartstay.amenity_catalog), 0),
    'service_catalog_count', coalesce((select count(*) from smartstay.service_catalog), 0),
    'legacy_utility_price_count', coalesce((
      select count(*)
      from smartstay.service_prices sp
      join smartstay.services s on s.id = sp.service_id
      where sp.service_catalog_id is null
        and lower(s.name) in ('electricity', 'water', 'electric', 'dien', 'nuoc')
    ), 0),
    'legacy_overlap_count', coalesce((
      select count(*)
      from smartstay.amenity_catalog ac
      join smartstay.service_catalog sc
        on sc.legacy_service_id = ac.legacy_service_id
       and ac.legacy_service_id is not null
    ), 0)
  );
$$;

grant execute on function smartstay.get_domain_schema_health() to authenticated, service_role;

create or replace function smartstay.create_contract_v2(
  p_room_id integer,
  p_start_date date,
  p_end_date date,
  p_monthly_rent numeric,
  p_deposit_amount numeric default 0,
  p_payment_cycle_months integer default 1,
  p_primary_tenant_id integer default null,
  p_occupant_ids integer[] default '{}'::integer[],
  p_payment_due_day smallint default 5,
  p_utility_policy_id bigint default null,
  p_service_ids bigint[] default '{}'::bigint[],
  p_service_prices numeric[] default '{}'::numeric[],
  p_service_quantities numeric[] default '{}'::numeric[],
  p_mark_deposit_received boolean default false
) returns jsonb
language plpgsql
security definer
set search_path = smartstay, public
as $$
declare
  v_contract_id integer;
  v_contract_code text;
  v_idx integer;
begin
  if p_room_id is null then
    raise exception 'room_id is required';
  end if;

  insert into smartstay.contracts (
    room_id,
    start_date,
    end_date,
    payment_cycle_months,
    payment_due_day,
    monthly_rent,
    deposit_amount,
    deposit_status,
    status,
    primary_tenant_id,
    occupants_for_billing,
    utility_billing_type,
    utility_policy_id,
    terms
  )
  values (
    p_room_id,
    p_start_date,
    p_end_date,
    coalesce(p_payment_cycle_months, 1),
    coalesce(p_payment_due_day, 5),
    p_monthly_rent,
    coalesce(p_deposit_amount, 0),
    case when coalesce(p_mark_deposit_received, false) then 'paid'::smartstay.deposit_status else 'pending'::smartstay.deposit_status end,
    'active'::smartstay.contract_status,
    p_primary_tenant_id,
    greatest(1, coalesce(array_length(p_occupant_ids, 1), 0) + case when p_primary_tenant_id is null then 0 else 1 end),
    'policy',
    p_utility_policy_id,
    jsonb_build_object(
      'occupants_for_billing',
      greatest(1, coalesce(array_length(p_occupant_ids, 1), 0) + case when p_primary_tenant_id is null then 0 else 1 end)
    )
  )
  returning id, contract_code into v_contract_id, v_contract_code;

  if p_primary_tenant_id is not null then
    insert into smartstay.contract_tenants (contract_id, tenant_id, is_primary)
    values (v_contract_id, p_primary_tenant_id, true)
    on conflict do nothing;

    insert into smartstay.room_occupants (
      contract_id,
      room_id,
      tenant_id,
      is_primary_tenant,
      move_in_at,
      status
    )
    values (
      v_contract_id,
      p_room_id,
      p_primary_tenant_id,
      true,
      p_start_date,
      'active'
    )
    on conflict do nothing;
  end if;

  if coalesce(array_length(p_occupant_ids, 1), 0) > 0 then
    insert into smartstay.contract_tenants (contract_id, tenant_id, is_primary)
    select v_contract_id, occupant_id, false
    from unnest(p_occupant_ids) as occupant_id
    on conflict do nothing;

    insert into smartstay.room_occupants (
      contract_id,
      room_id,
      tenant_id,
      is_primary_tenant,
      move_in_at,
      status
    )
    select
      v_contract_id,
      p_room_id,
      occupant_id,
      false,
      p_start_date,
      'active'
    from unnest(p_occupant_ids) as occupant_id
    on conflict do nothing;
  end if;

  if coalesce(array_length(p_service_ids, 1), 0) > 0 then
    for v_idx in 1..array_length(p_service_ids, 1) loop
      insert into smartstay.contract_services (
        contract_id,
        service_catalog_id,
        fixed_price,
        quantity
      )
      values (
        v_contract_id,
        p_service_ids[v_idx],
        coalesce(p_service_prices[v_idx], 0),
        coalesce(p_service_quantities[v_idx], 1)
      )
      on conflict (contract_id, service_catalog_id) do update
      set
        fixed_price = excluded.fixed_price,
        quantity = excluded.quantity;
    end loop;
  end if;

  update smartstay.rooms
  set status = 'occupied'::smartstay.room_status, updated_at = now()
  where id = p_room_id;

  return jsonb_build_object(
    'contractId', v_contract_id,
    'contractCode', v_contract_code
  );
end;
$$;

notify pgrst, 'reload schema';
